
# This file is automatically generated, you probably don't want to edit this

semljguiOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "semljguiOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            endogenous = NULL,
            factors = NULL,
            covs = NULL,
            multigroup = NULL,
            se = "standard",
            r2ci = "fisher",
            r2test = FALSE,
            bootci = "perc",
            ci = TRUE,
            ciWidth = 95,
            bootN = 1000,
            showintercepts = TRUE,
            intercepts = TRUE,
            indirect = FALSE,
            contrasts = NULL,
            showContrastCode = FALSE,
            scaling = NULL,
            endogenousTerms = list(
                list()),
            diagram = FALSE,
            diag_paths = "est",
            diag_resid = FALSE,
            diag_labsize = "medium",
            diag_rotate = "1",
            diag_type = "circle",
            diag_shape = "rectangle",
            diag_abbrev = "0",
            varcov = NULL,
            cov_y = TRUE,
            cov_x = TRUE,
            constraints = list(),
            syntax = NULL,
            code = NULL,
            constraints_examples = FALSE,
            showlabels = FALSE,
            scoretest = TRUE,
            cumscoretest = FALSE,
            estimator = "ML",
            likelihood = "normal", ...) {

            super$initialize(
                package="semlj",
                name="semljgui",
                requiresData=TRUE,
                ...)

            private$..endogenous <- jmvcore::OptionVariables$new(
                "endogenous",
                endogenous,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..multigroup <- jmvcore::OptionVariable$new(
                "multigroup",
                multigroup,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..se <- jmvcore::OptionList$new(
                "se",
                se,
                options=list(
                    "standard",
                    "robust.sem",
                    "robust.huber.white",
                    "boot"),
                default="standard")
            private$..r2ci <- jmvcore::OptionList$new(
                "r2ci",
                r2ci,
                options=list(
                    "fisher",
                    "model"),
                default="fisher")
            private$..r2test <- jmvcore::OptionBool$new(
                "r2test",
                r2test,
                default=FALSE)
            private$..bootci <- jmvcore::OptionList$new(
                "bootci",
                bootci,
                options=list(
                    "perc",
                    "bca.simple",
                    "norm",
                    "basic"),
                default="perc")
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=TRUE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..bootN <- jmvcore::OptionNumber$new(
                "bootN",
                bootN,
                min=50,
                default=1000)
            private$..showintercepts <- jmvcore::OptionBool$new(
                "showintercepts",
                showintercepts,
                default=TRUE)
            private$..intercepts <- jmvcore::OptionBool$new(
                "intercepts",
                intercepts,
                default=TRUE)
            private$..indirect <- jmvcore::OptionBool$new(
                "indirect",
                indirect,
                default=FALSE)
            private$..contrasts <- jmvcore::OptionArray$new(
                "contrasts",
                contrasts,
                items="(factors)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "contrasts",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "simple",
                                "deviation",
                                "dummy",
                                "difference",
                                "helmert",
                                "repeated",
                                "polynomial"),
                            default="simple"))))
            private$..showContrastCode <- jmvcore::OptionBool$new(
                "showContrastCode",
                showContrastCode,
                default=FALSE)
            private$..scaling <- jmvcore::OptionArray$new(
                "scaling",
                scaling,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "scaling",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "none",
                                "centered",
                                "standardized",
                                "log"),
                            default="none"))))
            private$..endogenousTerms <- jmvcore::OptionArray$new(
                "endogenousTerms",
                endogenousTerms,
                default=list(
                    list()),
                template=jmvcore::OptionTerms$new(
                    "endogenousTerms",
                    NULL))
            private$..diagram <- jmvcore::OptionBool$new(
                "diagram",
                diagram,
                default=FALSE)
            private$..diag_paths <- jmvcore::OptionList$new(
                "diag_paths",
                diag_paths,
                options=list(
                    "est",
                    "stand",
                    "name",
                    "hide"),
                default="est")
            private$..diag_resid <- jmvcore::OptionBool$new(
                "diag_resid",
                diag_resid,
                default=FALSE)
            private$..diag_labsize <- jmvcore::OptionList$new(
                "diag_labsize",
                diag_labsize,
                options=list(
                    "small",
                    "medium",
                    "large",
                    "vlarge"),
                default="medium")
            private$..diag_rotate <- jmvcore::OptionList$new(
                "diag_rotate",
                diag_rotate,
                options=list(
                    "1",
                    "2",
                    "3",
                    "4"),
                default="1")
            private$..diag_type <- jmvcore::OptionList$new(
                "diag_type",
                diag_type,
                options=list(
                    "circle",
                    "circle2",
                    "tree2",
                    "tree",
                    "spring"),
                default="circle")
            private$..diag_shape <- jmvcore::OptionList$new(
                "diag_shape",
                diag_shape,
                options=list(
                    "rectangle",
                    "square",
                    "circle",
                    "ellipse",
                    "diamond"),
                default="rectangle")
            private$..diag_abbrev <- jmvcore::OptionList$new(
                "diag_abbrev",
                diag_abbrev,
                options=list(
                    "0",
                    "5",
                    "10",
                    "15",
                    "20",
                    "25"),
                default="0")
            private$..varcov <- jmvcore::OptionPairs$new(
                "varcov",
                varcov)
            private$..cov_y <- jmvcore::OptionBool$new(
                "cov_y",
                cov_y,
                default=TRUE)
            private$..cov_x <- jmvcore::OptionBool$new(
                "cov_x",
                cov_x,
                default=TRUE)
            private$..constraints <- jmvcore::OptionArray$new(
                "constraints",
                constraints,
                default=list(),
                template=jmvcore::OptionString$new(
                    "constraints",
                    NULL))
            private$..syntax <- jmvcore::OptionString$new(
                "syntax",
                syntax,
                hidden=TRUE)
            private$..code <- jmvcore::OptionString$new(
                "code",
                code,
                hidden=TRUE)
            private$..constraints_examples <- jmvcore::OptionBool$new(
                "constraints_examples",
                constraints_examples,
                default=FALSE)
            private$..showlabels <- jmvcore::OptionBool$new(
                "showlabels",
                showlabels,
                default=FALSE)
            private$..scoretest <- jmvcore::OptionBool$new(
                "scoretest",
                scoretest,
                default=TRUE)
            private$..cumscoretest <- jmvcore::OptionBool$new(
                "cumscoretest",
                cumscoretest,
                default=FALSE)
            private$..estimator <- jmvcore::OptionList$new(
                "estimator",
                estimator,
                options=list(
                    "ML",
                    "GLS",
                    "WLS",
                    "DWLS",
                    "ULS"),
                default="ML")
            private$..likelihood <- jmvcore::OptionList$new(
                "likelihood",
                likelihood,
                options=list(
                    "normal",
                    "wishart"),
                default="normal")

            self$.addOption(private$..endogenous)
            self$.addOption(private$..factors)
            self$.addOption(private$..covs)
            self$.addOption(private$..multigroup)
            self$.addOption(private$..se)
            self$.addOption(private$..r2ci)
            self$.addOption(private$..r2test)
            self$.addOption(private$..bootci)
            self$.addOption(private$..ci)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..bootN)
            self$.addOption(private$..showintercepts)
            self$.addOption(private$..intercepts)
            self$.addOption(private$..indirect)
            self$.addOption(private$..contrasts)
            self$.addOption(private$..showContrastCode)
            self$.addOption(private$..scaling)
            self$.addOption(private$..endogenousTerms)
            self$.addOption(private$..diagram)
            self$.addOption(private$..diag_paths)
            self$.addOption(private$..diag_resid)
            self$.addOption(private$..diag_labsize)
            self$.addOption(private$..diag_rotate)
            self$.addOption(private$..diag_type)
            self$.addOption(private$..diag_shape)
            self$.addOption(private$..diag_abbrev)
            self$.addOption(private$..varcov)
            self$.addOption(private$..cov_y)
            self$.addOption(private$..cov_x)
            self$.addOption(private$..constraints)
            self$.addOption(private$..syntax)
            self$.addOption(private$..code)
            self$.addOption(private$..constraints_examples)
            self$.addOption(private$..showlabels)
            self$.addOption(private$..scoretest)
            self$.addOption(private$..cumscoretest)
            self$.addOption(private$..estimator)
            self$.addOption(private$..likelihood)
        }),
    active = list(
        endogenous = function() private$..endogenous$value,
        factors = function() private$..factors$value,
        covs = function() private$..covs$value,
        multigroup = function() private$..multigroup$value,
        se = function() private$..se$value,
        r2ci = function() private$..r2ci$value,
        r2test = function() private$..r2test$value,
        bootci = function() private$..bootci$value,
        ci = function() private$..ci$value,
        ciWidth = function() private$..ciWidth$value,
        bootN = function() private$..bootN$value,
        showintercepts = function() private$..showintercepts$value,
        intercepts = function() private$..intercepts$value,
        indirect = function() private$..indirect$value,
        contrasts = function() private$..contrasts$value,
        showContrastCode = function() private$..showContrastCode$value,
        scaling = function() private$..scaling$value,
        endogenousTerms = function() private$..endogenousTerms$value,
        diagram = function() private$..diagram$value,
        diag_paths = function() private$..diag_paths$value,
        diag_resid = function() private$..diag_resid$value,
        diag_labsize = function() private$..diag_labsize$value,
        diag_rotate = function() private$..diag_rotate$value,
        diag_type = function() private$..diag_type$value,
        diag_shape = function() private$..diag_shape$value,
        diag_abbrev = function() private$..diag_abbrev$value,
        varcov = function() private$..varcov$value,
        cov_y = function() private$..cov_y$value,
        cov_x = function() private$..cov_x$value,
        constraints = function() private$..constraints$value,
        syntax = function() private$..syntax$value,
        code = function() private$..code$value,
        constraints_examples = function() private$..constraints_examples$value,
        showlabels = function() private$..showlabels$value,
        scoretest = function() private$..scoretest$value,
        cumscoretest = function() private$..cumscoretest$value,
        estimator = function() private$..estimator$value,
        likelihood = function() private$..likelihood$value),
    private = list(
        ..endogenous = NA,
        ..factors = NA,
        ..covs = NA,
        ..multigroup = NA,
        ..se = NA,
        ..r2ci = NA,
        ..r2test = NA,
        ..bootci = NA,
        ..ci = NA,
        ..ciWidth = NA,
        ..bootN = NA,
        ..showintercepts = NA,
        ..intercepts = NA,
        ..indirect = NA,
        ..contrasts = NA,
        ..showContrastCode = NA,
        ..scaling = NA,
        ..endogenousTerms = NA,
        ..diagram = NA,
        ..diag_paths = NA,
        ..diag_resid = NA,
        ..diag_labsize = NA,
        ..diag_rotate = NA,
        ..diag_type = NA,
        ..diag_shape = NA,
        ..diag_abbrev = NA,
        ..varcov = NA,
        ..cov_y = NA,
        ..cov_x = NA,
        ..constraints = NA,
        ..syntax = NA,
        ..code = NA,
        ..constraints_examples = NA,
        ..showlabels = NA,
        ..scoretest = NA,
        ..cumscoretest = NA,
        ..estimator = NA,
        ..likelihood = NA)
)

semljguiResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "semljguiResults",
    inherit = jmvcore::Group,
    active = list(
        model = function() private$..model,
        info = function() private$.items[["info"]],
        fit = function() private$.items[["fit"]],
        models = function() private$.items[["models"]],
        pathgroup = function() private$.items[["pathgroup"]],
        contraintsnotes = function() private$.items[["contraintsnotes"]]),
    private = list(
        ..model = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="SEM for jamovi")
            private$..model <- NULL
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Models Info",
                clearWith=list(
                    "endogenousTerms",
                    "constraints"),
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`="", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="value", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="specs", 
                        `type`="text", 
                        `title`="", 
                        `combineBelow`=TRUE)),
                refs="pathj"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    main = function() private$.items[["main"]],
                    constraints = function() private$.items[["constraints"]],
                    indices = function() private$.items[["indices"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="fit",
                            title="Overall Tests",
                            clearWith=list(
                    "endogenousTerms"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="main",
                            title="Model Tests",
                            clearWith=list(
                                "endogenous",
                                "covs",
                                "factors",
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "constraints"),
                            columns=list(
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text"),
                                list(
                                    `name`="chisq", 
                                    `title`="X\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="integer"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="constraints",
                            title="Constraints Score Tests",
                            visible=FALSE,
                            clearWith=list(
                                "endogenous",
                                "covs",
                                "factors",
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "constraints"),
                            columns=list(
                                list(
                                    `name`="type", 
                                    `type`="text", 
                                    `title`="Type", 
                                    `visible`=TRUE, 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="lhs", 
                                    `title`="Par 1", 
                                    `type`="text"),
                                list(
                                    `name`="op", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="rhs", 
                                    `title`="Par 2", 
                                    `type`="text"),
                                list(
                                    `name`="chisq", 
                                    `title`="X\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="integer"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="indices",
                            title="Fit Indices",
                            clearWith=list(
                                "endogenous",
                                "covs",
                                "factors",
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "constraints"),
                            columns=list(
                                list(
                                    `name`="aic", 
                                    `title`="AIC", 
                                    `visible`="(estimator:ML)", 
                                    `type`="number"),
                                list(
                                    `name`="bic", 
                                    `title`="BIC", 
                                    `type`="number", 
                                    `visible`="(estimator:ML)"),
                                list(
                                    `name`="bic2", 
                                    `title`="adj. BIC", 
                                    `type`="number", 
                                    `visible`="(estimator:ML)"),
                                list(
                                    `name`="srmr", 
                                    `title`="SRMR", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="rmsea", 
                                    `title`="RMSEA", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="rmsea.ci.lower", 
                                    `title`="Lower", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="rmsea.ci.upper", 
                                    `title`="Upper", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="rmsea.pvalue", 
                                    `title`="RMSEA p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    r2 = function() private$.items[["r2"]],
                    coefficients = function() private$.items[["coefficients"]],
                    correlations = function() private$.items[["correlations"]],
                    intercepts = function() private$.items[["intercepts"]],
                    defined = function() private$.items[["defined"]],
                    contrastCodeTable = function() private$.items[["contrastCodeTable"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="models",
                            title="Estimates")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="r2",
                            title="R-squared",
                            clearWith=list(
                                "endogenous",
                                "covs",
                                "factors",
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "constraints",
                                "data",
                                "multigroup"),
                            columns=list(
                                list(
                                    `name`="lgroup", 
                                    `title`="Group", 
                                    `type`="text", 
                                    `visible`="(multigroup)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="lhs", 
                                    `title`="Variable", 
                                    `type`="text"),
                                list(
                                    `name`="r2", 
                                    `title`="R\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="chisq", 
                                    `title`="Wald X\u00B2", 
                                    `type`="number", 
                                    `visible`="(r2test)"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="integer", 
                                    `visible`="(r2test)"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue", 
                                    `visible`="(r2test)"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="coefficients",
                            title="Parameter Estimates",
                            refs="lavaan",
                            clearWith=list(
                                "endogenousTerms",
                                "endogenous",
                                "covs",
                                "factors",
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "constraints",
                                "data",
                                "multigroup"),
                            columns=list(
                                list(
                                    `name`="lgroup", 
                                    `title`="Group", 
                                    `type`="text", 
                                    `visible`="(multigroup)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text", 
                                    `visible`="(showlabels)"),
                                list(
                                    `name`="lhs", 
                                    `title`="Dep", 
                                    `type`="text"),
                                list(
                                    `name`="rhs", 
                                    `title`="Pred", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="correlations",
                            title="Variances and Covariances",
                            clearWith=list(
                                "endogenous",
                                "covs",
                                "factors",
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "constraints",
                                "data",
                                "multigroup",
                                "varcov"),
                            columns=list(
                                list(
                                    `name`="lgroup", 
                                    `title`="Group", 
                                    `type`="text", 
                                    `visible`="(multigroup)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text", 
                                    `visible`="(showlabels)"),
                                list(
                                    `name`="lhs", 
                                    `title`="Variable 1", 
                                    `type`="text"),
                                list(
                                    `name`="rhs", 
                                    `title`="Variable 2", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="user", 
                                    `title`="Method", 
                                    `type`="text"),
                                list(
                                    `name`="type", 
                                    `title`="Type", 
                                    `type`="text"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="intercepts",
                            title="Intercepts",
                            visible="(showintercepts)",
                            clearWith=list(
                                "endogenous",
                                "covs",
                                "factors",
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "constraints",
                                "data",
                                "multigroup"),
                            columns=list(
                                list(
                                    `name`="lgroup", 
                                    `title`="Group", 
                                    `type`="text", 
                                    `visible`="(multigroup)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text", 
                                    `visible`="(showlabels)"),
                                list(
                                    `name`="lhs", 
                                    `title`="Variable", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Intercept", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="defined",
                            title="Defined Parameters",
                            visible=FALSE,
                            clearWith=list(
                                "endogenous",
                                "covs",
                                "factors",
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "constraints",
                                "data",
                                "multigroup"),
                            columns=list(
                                list(
                                    `name`="lhs", 
                                    `title`="Label", 
                                    `type`="text"),
                                list(
                                    `name`="desc", 
                                    `title`="Description", 
                                    `type`="text"),
                                list(
                                    `name`="rhs", 
                                    `title`="Parameter", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2", 
                                    `format`="zto"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="contrastCodeTable",
                            title="Contrasts Definition",
                            visible=FALSE,
                            columns=list(
                                list(
                                    `name`="rname", 
                                    `title`="Name", 
                                    `type`="text"),
                                list(
                                    `name`="clab", 
                                    `title`="Contrast", 
                                    `type`="text"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    diagrams = function() private$.items[["diagrams"]],
                    notes = function() private$.items[["notes"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="pathgroup",
                            title="Path Model",
                            clearWith=list(
                    "endogenous",
                    "cov_y",
                    "constraints",
                    "varcov",
                    "data",
                    "multigroup"))
                        self$add(jmvcore::Array$new(
                            options=options,
                            name="diagrams",
                            title="Path Diagrams",
                            visible="(diagram)",
                            template=jmvcore::Image$new(
                                options=options,
                                title="$key",
                                renderFun=".showDiagram",
                                width=700,
                                height=500,
                                clearWith=list(
                                    "diag_resid",
                                    "diag_paths",
                                    "diag_labsize",
                                    "diag_rotate",
                                    "diag_type",
                                    "diag_shape",
                                    "diag_abbrev",
                                    "contrasts",
                                    "endogenousTerms",
                                    "cov_y",
                                    "constraints",
                                    "data",
                                    "multigroup",
                                    "varcov")),
                            refs="semplot"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="notes",
                            title="",
                            visible=FALSE,
                            columns=list(
                                list(
                                    `name`="message", 
                                    `type`="text", 
                                    `title`="Model diagram notes"))))}))$new(options=options))
            self$add(jmvcore::Table$new(
                options=options,
                name="contraintsnotes",
                visible="(constraints_examples)",
                title="Constraints input examples",
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`="Aim"),
                    list(
                        `name`="example", 
                        `type`="text", 
                        `title`="Example"),
                    list(
                        `name`="com", 
                        `type`="text", 
                        `title`="Outcome"))))},
        .setModel=function(x) private$..model <- x))

semljguiBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "semljguiBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "semlj",
                name = "semljgui",
                version = c(0,0,1),
                options = options,
                results = semljguiResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' SEM for jamovi
#'
#' Path Analysis
#' @param data the data as a data frame
#' @param endogenous a vector of strings naming the mediators from \code{data}
#' @param factors a vector of strings naming the fixed factors from
#'   \code{data}
#' @param covs a vector of strings naming the covariates from \code{data}
#' @param multigroup factor defining groups for multigroup analysis
#' @param se .
#' @param r2ci Choose the confidence interval type
#' @param r2test .
#' @param bootci Choose the confidence interval type
#' @param ci .
#' @param ciWidth a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width for the parameter estimates
#' @param bootN number of bootstrap samples for estimating confidence
#'   intervals
#' @param showintercepts \code{TRUE} or \code{FALSE} (default), show
#'   intercepts
#' @param intercepts \code{TRUE} or \code{FALSE} (default), show intercepts
#' @param indirect \code{TRUE} or \code{FALSE} (default), show intercepts
#' @param contrasts a list of lists specifying the factor and type of contrast
#'   to use, one of \code{'deviation'}, \code{'simple'}, \code{'difference'},
#'   \code{'helmert'}, \code{'repeated'} or \code{'polynomial'}
#' @param showContrastCode \code{TRUE} or \code{FALSE} (default), provide
#'   contrast coefficients tables
#' @param scaling a named vector of the form \code{c(var1='type',
#'   var2='type2')} specifying the transformation to apply to covariates, one of
#'   \code{'centered'} to the mean, \code{'standardized'},\code{'log'} or
#'   \code{'none'}. \code{'none'} leaves the variable as it is.
#' @param endogenousTerms a list of lists specifying the models for with the
#'   mediators as dependent variables.
#' @param diagram \code{TRUE} or \code{FALSE} (default), produce a path
#'   diagram
#' @param diag_paths Choose the diagram labels
#' @param diag_resid \code{TRUE} or \code{FALSE} (default), produce a path
#'   diagram
#' @param diag_labsize Choose the diagram labels
#' @param diag_rotate Choose the diagram labels
#' @param diag_type Choose the diagram labels
#' @param diag_shape Choose the diagram labels
#' @param diag_abbrev Choose the diagram labels
#' @param varcov a list of lists specifying the  covariances that need to be
#'   estimated
#' @param cov_y \code{TRUE} or \code{FALSE} (default), produce a path diagram
#' @param cov_x \code{TRUE} or \code{FALSE} (default), produce a path diagram
#' @param constraints a list of lists specifying the models random effects.
#' @param syntax .
#' @param code .
#' @param constraints_examples .
#' @param showlabels .
#' @param scoretest .
#' @param cumscoretest .
#' @param estimator Choose the diagram labels
#' @param likelihood Choose the diagram labels
#' @param formula (optional) the formula to use, see the examples
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$model} \tab \tab \tab \tab \tab The underlying \code{lavaan} object \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fit$main} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fit$constraints} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fit$indices} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$r2} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$coefficients} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$correlations} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$intercepts} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$defined} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$contrastCodeTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pathgroup$diagrams} \tab \tab \tab \tab \tab an array of path diagrams \cr
#'   \code{results$pathgroup$notes} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$contraintsnotes} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
semljgui <- function(
    data,
    endogenous = NULL,
    factors = NULL,
    covs = NULL,
    multigroup = NULL,
    se = "standard",
    r2ci = "fisher",
    r2test = FALSE,
    bootci = "perc",
    ci = TRUE,
    ciWidth = 95,
    bootN = 1000,
    showintercepts = TRUE,
    intercepts = TRUE,
    indirect = FALSE,
    contrasts = NULL,
    showContrastCode = FALSE,
    scaling = NULL,
    endogenousTerms = list(
                list()),
    diagram = FALSE,
    diag_paths = "est",
    diag_resid = FALSE,
    diag_labsize = "medium",
    diag_rotate = "1",
    diag_type = "circle",
    diag_shape = "rectangle",
    diag_abbrev = "0",
    varcov,
    cov_y = TRUE,
    cov_x = TRUE,
    constraints = list(),
    syntax,
    code,
    constraints_examples = FALSE,
    showlabels = FALSE,
    scoretest = TRUE,
    cumscoretest = FALSE,
    estimator = "ML",
    likelihood = "normal",
    formula) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("semljgui requires jmvcore to be installed (restart may be required)")

    if ( ! missing(formula)) {
        if (missing(endogenous))
            endogenous <- semljguiClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="endogenous")
        if (missing(endogenousTerms))
            endogenousTerms <- semljguiClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="endogenousTerms")
        if (missing(factors))
            factors <- semljguiClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="factors")
        if (missing(covs))
            covs <- semljguiClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="covs")
    }

    if ( ! missing(endogenous)) endogenous <- jmvcore::resolveQuo(jmvcore::enquo(endogenous))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(multigroup)) multigroup <- jmvcore::resolveQuo(jmvcore::enquo(multigroup))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(endogenous), endogenous, NULL),
            `if`( ! missing(factors), factors, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(multigroup), multigroup, NULL))

    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in multigroup) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- semljguiOptions$new(
        endogenous = endogenous,
        factors = factors,
        covs = covs,
        multigroup = multigroup,
        se = se,
        r2ci = r2ci,
        r2test = r2test,
        bootci = bootci,
        ci = ci,
        ciWidth = ciWidth,
        bootN = bootN,
        showintercepts = showintercepts,
        intercepts = intercepts,
        indirect = indirect,
        contrasts = contrasts,
        showContrastCode = showContrastCode,
        scaling = scaling,
        endogenousTerms = endogenousTerms,
        diagram = diagram,
        diag_paths = diag_paths,
        diag_resid = diag_resid,
        diag_labsize = diag_labsize,
        diag_rotate = diag_rotate,
        diag_type = diag_type,
        diag_shape = diag_shape,
        diag_abbrev = diag_abbrev,
        varcov = varcov,
        cov_y = cov_y,
        cov_x = cov_x,
        constraints = constraints,
        syntax = syntax,
        code = code,
        constraints_examples = constraints_examples,
        showlabels = showlabels,
        scoretest = scoretest,
        cumscoretest = cumscoretest,
        estimator = estimator,
        likelihood = likelihood)

    analysis <- semljguiClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

