
# This file is automatically generated, you probably don't want to edit this

semljsynOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "semljsynOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            code = "",
            syntax = NULL,
            fonts = "small",
            vars = NULL,
            toggle = FALSE,
            estimator = "ML",
            likelihood = "normal",
            scoretest = TRUE,
            cumscoretest = FALSE,
            se = "standard",
            bootci = "perc",
            bootN = 1000,
            ci = TRUE,
            ciWidth = 95,
            intercepts = TRUE,
            showintercepts = TRUE,
            indirect = FALSE,
            auto.fix.first = TRUE,
            std.lv = FALSE,
            cov_x = TRUE,
            cov_y = TRUE,
            multigroup = NULL,
            eq_loadings = FALSE,
            eq_intercepts = FALSE,
            eq_residuals = FALSE,
            eq_residual.covariances = FALSE,
            eq_means = FALSE,
            eq_thresholds = FALSE,
            eq_regressions = FALSE,
            eq_lv.variances = FALSE,
            eq_lv.covariances = FALSE,
            showlabels = FALSE,
            constraints_examples = FALSE,
            outputAdditionalFitMeasures = FALSE,
            outputRSquared = FALSE,
            outputMardiasCoefficients = FALSE,
            outputObservedCovariances = FALSE,
            outputImpliedCovariances = FALSE,
            outputResidualCovariances = FALSE,
            outpuCombineCovariances = FALSE,
            outputModificationIndices = FALSE,
            miHideLow = FALSE,
            miThreshold = 10,
            diagram = FALSE,
            diag_resid = FALSE,
            diag_intercepts = FALSE,
            diag_paths = "est",
            diag_type = "tree",
            diag_rotate = "2",
            diag_labsize = "medium",
            diag_shape_man = "rectangle",
            diag_shape_lat = "circle",
            diag_abbrev = "5", ...) {

            super$initialize(
                package="semlj",
                name="semljsyn",
                requiresData=TRUE,
                ...)

            private$..code <- jmvcore::OptionString$new(
                "code",
                code,
                default="",
                hidden=TRUE)
            private$..syntax <- jmvcore::OptionString$new(
                "syntax",
                syntax,
                hidden=TRUE)
            private$..fonts <- jmvcore::OptionString$new(
                "fonts",
                fonts,
                default="small",
                hidden=TRUE)
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                hidden=TRUE,
                permitted=list(
                    "factor",
                    "numeric",
                    "id"))
            private$..toggle <- jmvcore::OptionBool$new(
                "toggle",
                toggle,
                default=FALSE,
                hidden=TRUE)
            private$..estimator <- jmvcore::OptionList$new(
                "estimator",
                estimator,
                options=list(
                    "ML",
                    "GLS",
                    "WLS",
                    "DWLS",
                    "ULS"),
                default="ML")
            private$..likelihood <- jmvcore::OptionList$new(
                "likelihood",
                likelihood,
                options=list(
                    "normal",
                    "wishart"),
                default="normal")
            private$..scoretest <- jmvcore::OptionBool$new(
                "scoretest",
                scoretest,
                default=TRUE)
            private$..cumscoretest <- jmvcore::OptionBool$new(
                "cumscoretest",
                cumscoretest,
                default=FALSE)
            private$..se <- jmvcore::OptionList$new(
                "se",
                se,
                options=list(
                    "standard",
                    "robust.sem",
                    "robust.huber.white",
                    "boot"),
                default="standard")
            private$..bootci <- jmvcore::OptionList$new(
                "bootci",
                bootci,
                options=list(
                    "perc",
                    "bca.simple",
                    "norm",
                    "basic"),
                default="perc")
            private$..bootN <- jmvcore::OptionNumber$new(
                "bootN",
                bootN,
                min=50,
                default=1000)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=TRUE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..intercepts <- jmvcore::OptionBool$new(
                "intercepts",
                intercepts,
                default=TRUE)
            private$..showintercepts <- jmvcore::OptionBool$new(
                "showintercepts",
                showintercepts,
                default=TRUE)
            private$..indirect <- jmvcore::OptionBool$new(
                "indirect",
                indirect,
                default=FALSE)
            private$..auto.fix.first <- jmvcore::OptionBool$new(
                "auto.fix.first",
                auto.fix.first,
                default=TRUE)
            private$..std.lv <- jmvcore::OptionBool$new(
                "std.lv",
                std.lv,
                default=FALSE)
            private$..cov_x <- jmvcore::OptionBool$new(
                "cov_x",
                cov_x,
                default=TRUE)
            private$..cov_y <- jmvcore::OptionBool$new(
                "cov_y",
                cov_y,
                default=TRUE)
            private$..multigroup <- jmvcore::OptionString$new(
                "multigroup",
                multigroup)
            private$..eq_loadings <- jmvcore::OptionBool$new(
                "eq_loadings",
                eq_loadings,
                default=FALSE)
            private$..eq_intercepts <- jmvcore::OptionBool$new(
                "eq_intercepts",
                eq_intercepts,
                default=FALSE)
            private$..eq_residuals <- jmvcore::OptionBool$new(
                "eq_residuals",
                eq_residuals,
                default=FALSE)
            private$..eq_residual.covariances <- jmvcore::OptionBool$new(
                "eq_residual.covariances",
                eq_residual.covariances,
                default=FALSE)
            private$..eq_means <- jmvcore::OptionBool$new(
                "eq_means",
                eq_means,
                default=FALSE)
            private$..eq_thresholds <- jmvcore::OptionBool$new(
                "eq_thresholds",
                eq_thresholds,
                default=FALSE)
            private$..eq_regressions <- jmvcore::OptionBool$new(
                "eq_regressions",
                eq_regressions,
                default=FALSE)
            private$..eq_lv.variances <- jmvcore::OptionBool$new(
                "eq_lv.variances",
                eq_lv.variances,
                default=FALSE)
            private$..eq_lv.covariances <- jmvcore::OptionBool$new(
                "eq_lv.covariances",
                eq_lv.covariances,
                default=FALSE)
            private$..showlabels <- jmvcore::OptionBool$new(
                "showlabels",
                showlabels,
                default=FALSE)
            private$..constraints_examples <- jmvcore::OptionBool$new(
                "constraints_examples",
                constraints_examples,
                default=FALSE)
            private$..outputAdditionalFitMeasures <- jmvcore::OptionBool$new(
                "outputAdditionalFitMeasures",
                outputAdditionalFitMeasures,
                default=FALSE)
            private$..outputRSquared <- jmvcore::OptionBool$new(
                "outputRSquared",
                outputRSquared,
                default=FALSE)
            private$..outputMardiasCoefficients <- jmvcore::OptionBool$new(
                "outputMardiasCoefficients",
                outputMardiasCoefficients,
                default=FALSE)
            private$..outputObservedCovariances <- jmvcore::OptionBool$new(
                "outputObservedCovariances",
                outputObservedCovariances,
                default=FALSE)
            private$..outputImpliedCovariances <- jmvcore::OptionBool$new(
                "outputImpliedCovariances",
                outputImpliedCovariances,
                default=FALSE)
            private$..outputResidualCovariances <- jmvcore::OptionBool$new(
                "outputResidualCovariances",
                outputResidualCovariances,
                default=FALSE)
            private$..outpuCombineCovariances <- jmvcore::OptionBool$new(
                "outpuCombineCovariances",
                outpuCombineCovariances,
                default=FALSE)
            private$..outputModificationIndices <- jmvcore::OptionBool$new(
                "outputModificationIndices",
                outputModificationIndices,
                default=FALSE)
            private$..miHideLow <- jmvcore::OptionBool$new(
                "miHideLow",
                miHideLow,
                default=FALSE)
            private$..miThreshold <- jmvcore::OptionNumber$new(
                "miThreshold",
                miThreshold,
                default=10,
                min=0)
            private$..diagram <- jmvcore::OptionBool$new(
                "diagram",
                diagram,
                default=FALSE)
            private$..diag_resid <- jmvcore::OptionBool$new(
                "diag_resid",
                diag_resid,
                default=FALSE)
            private$..diag_intercepts <- jmvcore::OptionBool$new(
                "diag_intercepts",
                diag_intercepts,
                default=FALSE)
            private$..diag_paths <- jmvcore::OptionList$new(
                "diag_paths",
                diag_paths,
                options=list(
                    "est",
                    "stand",
                    "name",
                    "hide"),
                default="est")
            private$..diag_type <- jmvcore::OptionList$new(
                "diag_type",
                diag_type,
                options=list(
                    "tree",
                    "tree2",
                    "circle",
                    "circle2",
                    "spring"),
                default="tree")
            private$..diag_rotate <- jmvcore::OptionList$new(
                "diag_rotate",
                diag_rotate,
                options=list(
                    "1",
                    "2",
                    "3",
                    "4"),
                default="2")
            private$..diag_labsize <- jmvcore::OptionList$new(
                "diag_labsize",
                diag_labsize,
                options=list(
                    "small",
                    "medium",
                    "large",
                    "vlarge"),
                default="medium")
            private$..diag_shape_man <- jmvcore::OptionList$new(
                "diag_shape_man",
                diag_shape_man,
                options=list(
                    "rectangle",
                    "square",
                    "circle",
                    "ellipse",
                    "diamond"),
                default="rectangle")
            private$..diag_shape_lat <- jmvcore::OptionList$new(
                "diag_shape_lat",
                diag_shape_lat,
                options=list(
                    "circle",
                    "rectangle",
                    "square",
                    "ellipse",
                    "diamond"),
                default="circle")
            private$..diag_abbrev <- jmvcore::OptionList$new(
                "diag_abbrev",
                diag_abbrev,
                options=list(
                    "0",
                    "5",
                    "10",
                    "15",
                    "20",
                    "25"),
                default="5")

            self$.addOption(private$..code)
            self$.addOption(private$..syntax)
            self$.addOption(private$..fonts)
            self$.addOption(private$..vars)
            self$.addOption(private$..toggle)
            self$.addOption(private$..estimator)
            self$.addOption(private$..likelihood)
            self$.addOption(private$..scoretest)
            self$.addOption(private$..cumscoretest)
            self$.addOption(private$..se)
            self$.addOption(private$..bootci)
            self$.addOption(private$..bootN)
            self$.addOption(private$..ci)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..intercepts)
            self$.addOption(private$..showintercepts)
            self$.addOption(private$..indirect)
            self$.addOption(private$..auto.fix.first)
            self$.addOption(private$..std.lv)
            self$.addOption(private$..cov_x)
            self$.addOption(private$..cov_y)
            self$.addOption(private$..multigroup)
            self$.addOption(private$..eq_loadings)
            self$.addOption(private$..eq_intercepts)
            self$.addOption(private$..eq_residuals)
            self$.addOption(private$..eq_residual.covariances)
            self$.addOption(private$..eq_means)
            self$.addOption(private$..eq_thresholds)
            self$.addOption(private$..eq_regressions)
            self$.addOption(private$..eq_lv.variances)
            self$.addOption(private$..eq_lv.covariances)
            self$.addOption(private$..showlabels)
            self$.addOption(private$..constraints_examples)
            self$.addOption(private$..outputAdditionalFitMeasures)
            self$.addOption(private$..outputRSquared)
            self$.addOption(private$..outputMardiasCoefficients)
            self$.addOption(private$..outputObservedCovariances)
            self$.addOption(private$..outputImpliedCovariances)
            self$.addOption(private$..outputResidualCovariances)
            self$.addOption(private$..outpuCombineCovariances)
            self$.addOption(private$..outputModificationIndices)
            self$.addOption(private$..miHideLow)
            self$.addOption(private$..miThreshold)
            self$.addOption(private$..diagram)
            self$.addOption(private$..diag_resid)
            self$.addOption(private$..diag_intercepts)
            self$.addOption(private$..diag_paths)
            self$.addOption(private$..diag_type)
            self$.addOption(private$..diag_rotate)
            self$.addOption(private$..diag_labsize)
            self$.addOption(private$..diag_shape_man)
            self$.addOption(private$..diag_shape_lat)
            self$.addOption(private$..diag_abbrev)
        }),
    active = list(
        code = function() private$..code$value,
        syntax = function() private$..syntax$value,
        fonts = function() private$..fonts$value,
        vars = function() private$..vars$value,
        toggle = function() private$..toggle$value,
        estimator = function() private$..estimator$value,
        likelihood = function() private$..likelihood$value,
        scoretest = function() private$..scoretest$value,
        cumscoretest = function() private$..cumscoretest$value,
        se = function() private$..se$value,
        bootci = function() private$..bootci$value,
        bootN = function() private$..bootN$value,
        ci = function() private$..ci$value,
        ciWidth = function() private$..ciWidth$value,
        intercepts = function() private$..intercepts$value,
        showintercepts = function() private$..showintercepts$value,
        indirect = function() private$..indirect$value,
        auto.fix.first = function() private$..auto.fix.first$value,
        std.lv = function() private$..std.lv$value,
        cov_x = function() private$..cov_x$value,
        cov_y = function() private$..cov_y$value,
        multigroup = function() private$..multigroup$value,
        eq_loadings = function() private$..eq_loadings$value,
        eq_intercepts = function() private$..eq_intercepts$value,
        eq_residuals = function() private$..eq_residuals$value,
        eq_residual.covariances = function() private$..eq_residual.covariances$value,
        eq_means = function() private$..eq_means$value,
        eq_thresholds = function() private$..eq_thresholds$value,
        eq_regressions = function() private$..eq_regressions$value,
        eq_lv.variances = function() private$..eq_lv.variances$value,
        eq_lv.covariances = function() private$..eq_lv.covariances$value,
        showlabels = function() private$..showlabels$value,
        constraints_examples = function() private$..constraints_examples$value,
        outputAdditionalFitMeasures = function() private$..outputAdditionalFitMeasures$value,
        outputRSquared = function() private$..outputRSquared$value,
        outputMardiasCoefficients = function() private$..outputMardiasCoefficients$value,
        outputObservedCovariances = function() private$..outputObservedCovariances$value,
        outputImpliedCovariances = function() private$..outputImpliedCovariances$value,
        outputResidualCovariances = function() private$..outputResidualCovariances$value,
        outpuCombineCovariances = function() private$..outpuCombineCovariances$value,
        outputModificationIndices = function() private$..outputModificationIndices$value,
        miHideLow = function() private$..miHideLow$value,
        miThreshold = function() private$..miThreshold$value,
        diagram = function() private$..diagram$value,
        diag_resid = function() private$..diag_resid$value,
        diag_intercepts = function() private$..diag_intercepts$value,
        diag_paths = function() private$..diag_paths$value,
        diag_type = function() private$..diag_type$value,
        diag_rotate = function() private$..diag_rotate$value,
        diag_labsize = function() private$..diag_labsize$value,
        diag_shape_man = function() private$..diag_shape_man$value,
        diag_shape_lat = function() private$..diag_shape_lat$value,
        diag_abbrev = function() private$..diag_abbrev$value),
    private = list(
        ..code = NA,
        ..syntax = NA,
        ..fonts = NA,
        ..vars = NA,
        ..toggle = NA,
        ..estimator = NA,
        ..likelihood = NA,
        ..scoretest = NA,
        ..cumscoretest = NA,
        ..se = NA,
        ..bootci = NA,
        ..bootN = NA,
        ..ci = NA,
        ..ciWidth = NA,
        ..intercepts = NA,
        ..showintercepts = NA,
        ..indirect = NA,
        ..auto.fix.first = NA,
        ..std.lv = NA,
        ..cov_x = NA,
        ..cov_y = NA,
        ..multigroup = NA,
        ..eq_loadings = NA,
        ..eq_intercepts = NA,
        ..eq_residuals = NA,
        ..eq_residual.covariances = NA,
        ..eq_means = NA,
        ..eq_thresholds = NA,
        ..eq_regressions = NA,
        ..eq_lv.variances = NA,
        ..eq_lv.covariances = NA,
        ..showlabels = NA,
        ..constraints_examples = NA,
        ..outputAdditionalFitMeasures = NA,
        ..outputRSquared = NA,
        ..outputMardiasCoefficients = NA,
        ..outputObservedCovariances = NA,
        ..outputImpliedCovariances = NA,
        ..outputResidualCovariances = NA,
        ..outpuCombineCovariances = NA,
        ..outputModificationIndices = NA,
        ..miHideLow = NA,
        ..miThreshold = NA,
        ..diagram = NA,
        ..diag_resid = NA,
        ..diag_intercepts = NA,
        ..diag_paths = NA,
        ..diag_type = NA,
        ..diag_rotate = NA,
        ..diag_labsize = NA,
        ..diag_shape_man = NA,
        ..diag_shape_lat = NA,
        ..diag_abbrev = NA)
)

semljsynResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "semljsynResults",
    inherit = jmvcore::Group,
    active = list(
        model = function() private$..model,
        info = function() private$.items[["info"]],
        contraintsnotes = function() private$.items[["contraintsnotes"]],
        fit = function() private$.items[["fit"]],
        models = function() private$.items[["models"]],
        add_outputs = function() private$.items[["add_outputs"]],
        group_covariances = function() private$.items[["group_covariances"]],
        modgroup = function() private$.items[["modgroup"]],
        pathgroup = function() private$.items[["pathgroup"]]),
    private = list(
        ..model = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Structural Equation Modelling")
            private$..model <- NULL
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Models Info",
                clearWith=list(
                    "code"),
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`="", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="value", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="specs", 
                        `type`="text", 
                        `title`="", 
                        `combineBelow`=TRUE)),
                refs="semlj"))
            self$add(jmvcore::Table$new(
                options=options,
                name="contraintsnotes",
                visible="(constraints_examples)",
                title="Syntax examples",
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`="Aim"),
                    list(
                        `name`="example", 
                        `type`="text", 
                        `title`="Example"),
                    list(
                        `name`="com", 
                        `type`="text", 
                        `title`="Outcome"))))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    main = function() private$.items[["main"]],
                    constraints = function() private$.items[["constraints"]],
                    indices = function() private$.items[["indices"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="fit",
                            title="Overall Tests",
                            clearWith=list(
                    "code"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="main",
                            title="Model tests",
                            clearWith=list(
                                "ciType",
                                "cov_y",
                                "code"),
                            columns=list(
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text"),
                                list(
                                    `name`="chisq", 
                                    `title`="X\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="integer"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="constraints",
                            title="Constraints score tests",
                            visible=FALSE,
                            clearWith=list(
                                "ciType",
                                "cov_y",
                                "code"),
                            columns=list(
                                list(
                                    `name`="type", 
                                    `type`="text", 
                                    `title`="Type", 
                                    `visible`=TRUE, 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="lhs", 
                                    `title`="Par 1", 
                                    `type`="text"),
                                list(
                                    `name`="op", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="rhs", 
                                    `title`="Par 2", 
                                    `type`="text"),
                                list(
                                    `name`="chisq", 
                                    `title`="X\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="integer"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="indices",
                            title="Fit indices",
                            clearWith=list(
                                "endogenous",
                                "covs",
                                "factors",
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "constraints"),
                            columns=list(
                                list(
                                    `name`="aic", 
                                    `title`="AIC", 
                                    `visible`="(estimator:ML)", 
                                    `type`="number"),
                                list(
                                    `name`="bic", 
                                    `title`="BIC", 
                                    `type`="number", 
                                    `visible`="(estimator:ML)"),
                                list(
                                    `name`="bic2", 
                                    `title`="adj. BIC", 
                                    `type`="number", 
                                    `visible`="(estimator:ML)"),
                                list(
                                    `name`="srmr", 
                                    `title`="SRMR", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="rmsea", 
                                    `title`="RMSEA", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="rmsea.ci.lower", 
                                    `title`="Lower", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="rmsea.ci.upper", 
                                    `title`="Upper", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="rmsea.pvalue", 
                                    `title`="RMSEA p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    coefficients = function() private$.items[["coefficients"]],
                    loadings = function() private$.items[["loadings"]],
                    intercepts = function() private$.items[["intercepts"]],
                    defined = function() private$.items[["defined"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="models",
                            title="Estimates")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="coefficients",
                            title="Parameter estimates",
                            refs="lavaan",
                            clearWith=list(
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "data",
                                "multigroup",
                                "code"),
                            columns=list(
                                list(
                                    `name`="lgroup", 
                                    `title`="Group", 
                                    `type`="text", 
                                    `visible`="(multigroup)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text", 
                                    `visible`="(showlabels)"),
                                list(
                                    `name`="lhs", 
                                    `title`="Dep", 
                                    `type`="text"),
                                list(
                                    `name`="rhs", 
                                    `title`="Pred", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="loadings",
                            title="Measurement model",
                            visible=FALSE,
                            clearWith=list(
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "data",
                                "multigroup",
                                "code"),
                            columns=list(
                                list(
                                    `name`="lgroup", 
                                    `title`="Group", 
                                    `type`="text", 
                                    `visible`="(multigroup)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text", 
                                    `visible`="(showlabels)"),
                                list(
                                    `name`="lhs", 
                                    `title`="Latent", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="rhs", 
                                    `title`="Observed", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="intercepts",
                            title="Intercepts",
                            visible=FALSE,
                            clearWith=list(
                                "ciType",
                                "cov_y",
                                "data",
                                "multigroup",
                                "code"),
                            columns=list(
                                list(
                                    `name`="lgroup", 
                                    `title`="Group", 
                                    `type`="text", 
                                    `visible`="(multigroup)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text", 
                                    `visible`="(showlabels)"),
                                list(
                                    `name`="lhs", 
                                    `title`="Variable", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Intercept", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="defined",
                            title="Defined parameters",
                            visible=FALSE,
                            clearWith=list(
                                "ciType",
                                "cov_y",
                                "data",
                                "multigroup",
                                "code"),
                            columns=list(
                                list(
                                    `name`="lhs", 
                                    `title`="Label", 
                                    `type`="text"),
                                list(
                                    `name`="desc", 
                                    `title`="Description", 
                                    `type`="text"),
                                list(
                                    `name`="rhs", 
                                    `title`="Parameter", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2", 
                                    `format`="zto"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    compModelBsl = function() private$.items[["compModelBsl"]],
                    otherFit = function() private$.items[["otherFit"]],
                    Rsquared = function() private$.items[["Rsquared"]],
                    mardia = function() private$.items[["mardia"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="add_outputs",
                            title="Additional outputs")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="compModelBsl",
                            title="User model versus baseline model",
                            visible="(outputAdditionalFitMeasures)",
                            clearWith=NULL,
                            rows=8,
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="statistics", 
                                    `title`="Model", 
                                    `type`="number", 
                                    `format`="zto"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="otherFit",
                            title="Other fit indices",
                            visible="(outputAdditionalFitMeasures)",
                            clearWith=NULL,
                            rows=5,
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="statistics", 
                                    `title`="Model", 
                                    `type`="number"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="Rsquared",
                            title="R\u00B2-values of the endogenous variables",
                            visible="(outputRSquared)",
                            clearWith=NULL,
                            columns=list(
                                list(
                                    `name`="rhs", 
                                    `title`="Variable", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="R\u00B2", 
                                    `type`="number"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="mardia",
                            title="Mardia's coefficients",
                            visible="(outputMardiasCoefficients)",
                            clearWith=NULL,
                            rows=2,
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="coeff", 
                                    `title`="Coefficient", 
                                    `type`="number"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="chi", 
                                    `title`="\u03C7\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="integer"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    covcorrObserved = function() private$.items[["covcorrObserved"]],
                    covcorrImplied = function() private$.items[["covcorrImplied"]],
                    covcorrResidual = function() private$.items[["covcorrResidual"]],
                    covcorrCombined = function() private$.items[["covcorrCombined"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="group_covariances",
                            title="Covariances and correlations")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="covcorrObserved",
                            title="Observed covariances (lower triangle) and correlations (upper triangle)",
                            visible=FALSE,
                            clearWith=list(
                                "ciType",
                                "cov_y",
                                "data",
                                "multigroup",
                                "code"),
                            columns=list(
                                list(
                                    `name`="variable", 
                                    `title`="", 
                                    `type`="text"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="covcorrImplied",
                            title="Fitted covariances (lower triangle) and correlations (upper triangle)",
                            visible=FALSE,
                            clearWith=list(
                                "ciType",
                                "cov_y",
                                "data",
                                "multigroup",
                                "code"),
                            columns=list(
                                list(
                                    `name`="variable", 
                                    `title`="", 
                                    `type`="text"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="covcorrResidual",
                            title="Residual covariances (lower triangle) and correlations (upper triangle)",
                            visible=FALSE,
                            clearWith=list(
                                "ciType",
                                "cov_y",
                                "data",
                                "multigroup",
                                "code"),
                            columns=list(
                                list(
                                    `name`="variable", 
                                    `title`="", 
                                    `type`="text"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="covcorrCombined",
                            title="Covariances (lower triangle) and correlations (upper triangle)",
                            visible=FALSE,
                            clearWith=list(
                                "ciType",
                                "cov_y",
                                "data",
                                "multigroup",
                                "code"),
                            columns=list(
                                list(
                                    `name`="variable", 
                                    `title`="", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="type", 
                                    `title`="", 
                                    `type`="text"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    modInd = function() private$.items[["modInd"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="modgroup",
                            title="Modifcation indices",
                            clearWith=list(
                    "ciType",
                    "cov_y",
                    "data",
                    "multigroup",
                    "code"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="modInd",
                            title="Modification indices",
                            visible="(outputModificationIndices)",
                            notes=list(
                                `EPC`="expected parameter changes and their standardized forms (sEPC); for latent variables (LV), all variables (all), and latent and observed variables except for the exogenous observed variables (nox)"),
                            columns=list(
                                list(
                                    `name`="lhs", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="op", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="rhs", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="mi", 
                                    `title`="Modif. index", 
                                    `type`="number"),
                                list(
                                    `name`="epc", 
                                    `title`="EPC", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="sepc.lv", 
                                    `title`="sEPC (LV)", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="sepc.all", 
                                    `title`="sEPC (all)", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="sepc.nox", 
                                    `title`="sEPC (nox)", 
                                    `type`="number", 
                                    `format`="zto"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    diagrams = function() private$.items[["diagrams"]],
                    notes = function() private$.items[["notes"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="pathgroup",
                            title="Path Model",
                            clearWith=list(
                    "cov_y",
                    "data",
                    "multigroup",
                    "code",
                    "diag_shape_man",
                    "diag_shape_lat",
                    "diag_abbrev",
                    "diag_type",
                    "diag_rotate",
                    "diag_labsize",
                    "diag_resid",
                    "diag_paths",
                    "dia_intercepts"))
                        self$add(jmvcore::Array$new(
                            options=options,
                            name="diagrams",
                            title="Path diagrams",
                            visible="(diagram)",
                            template=jmvcore::Image$new(
                                options=options,
                                title="$key",
                                renderFun=".showDiagram",
                                width=800,
                                height=600,
                                clearWith=list(
                                    "cov_y",
                                    "data",
                                    "multigroup",
                                    "code",
                                    "diag_shape_man",
                                    "diag_shape_lat",
                                    "diag_abbrev",
                                    "diag_type",
                                    "diag_rotate",
                                    "diag_labsize",
                                    "diag_resid",
                                    "diag_paths",
                                    "diag_intercepts"),
                                refs="semplot")))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="notes",
                            title="",
                            visible=FALSE,
                            columns=list(
                                list(
                                    `name`="message", 
                                    `type`="text", 
                                    `title`="Model diagram notes"))))}))$new(options=options))},
        .setModel=function(x) private$..model <- x))

semljsynBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "semljsynBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "semlj",
                name = "semljsyn",
                version = c(1,0,0),
                options = options,
                results = semljsynResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Structural Equation Models
#'
#' 
#' @param data TO ADD
#' @param code TO ADD
#' @param syntax .
#' @param fonts .
#' @param vars .
#' @param toggle .
#' @param estimator TO ADD
#' @param likelihood TO ADD
#' @param scoretest TO ADD
#' @param cumscoretest TO ADD
#' @param se TO ADD
#' @param bootci choose the confidence interval type ("perc" - percentiles
#'   [default], "bca.simple" - adjusted bias-corrected, "norm" - normal, "basic"
#'   - basic)
#' @param bootN number of bootstrap samples for estimating confidence
#'   intervals
#' @param ci \code{TRUE} or \code{FALSE} (default), show confidence intervals
#' @param ciWidth a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width for the parameter estimates
#' @param intercepts \code{TRUE} or \code{FALSE} (default), show intercepts
#' @param showintercepts \code{TRUE} or \code{FALSE} (default), show
#'   intercepts
#' @param indirect \code{TRUE} or \code{FALSE} (default), show intercepts
#' @param auto.fix.first \code{TRUE} or \code{FALSE}
#' @param std.lv \code{TRUE} or \code{FALSE}
#' @param cov_x \code{TRUE} (default) or \code{FALSE}, fix exogenous
#'   covariates
#' @param cov_y \code{TRUE} (default) or \code{FALSE}, TO ADD
#' @param multigroup string (default=""), the separate models (one for each
#'   level / group in the variable) are fit, instead of fitting the same model
#'   for the whole dataset (all groups)
#' @param eq_loadings \code{TRUE} or \code{FALSE} (default), constrain the
#'   factor loadings to be equal across groups (when conducting multi-group
#'   analyses)
#' @param eq_intercepts \code{TRUE} or \code{FALSE} (default), constrain the
#'   intercepts of the observed variables to be equal across groups (when
#'   conducting multi-group analyses)
#' @param eq_residuals \code{TRUE} or \code{FALSE} (default), constrain the
#'   residual variances of the observed variables to be equal across groups
#'   (when conducting multi-group analyses)
#' @param eq_residual.covariances \code{TRUE} or \code{FALSE} (default),
#'   constrain the residual covariances of the observed variables to be equal
#'   across groups (when conducting multi-group analyses)
#' @param eq_means \code{TRUE} or \code{FALSE} (default), constrain the
#'   intercepts / means of the latent variables to be equal across groups (when
#'   conducting multi-group analyses)
#' @param eq_thresholds \code{TRUE} or \code{FALSE} (default), constrain the
#'   sample-based thresholds (means for continuous observed mvariables) to be
#'   equal across groups (when conducting multi-group analyses)
#' @param eq_regressions \code{TRUE} or \code{FALSE} (default), constrain all
#'   regression coefficients in the model to be equal across groups (when
#'   conducting multi-group analyses)
#' @param eq_lv.variances \code{TRUE} or \code{FALSE} (default), constrain the
#'   (residual) variances of the latent variables to be equal across groups
#'   (when conducting multi-group analyses)
#' @param eq_lv.covariances \code{TRUE} or \code{FALSE} (default), constrain
#'   the (residual) covariances of the latent variables to be equal across
#'   groups (when conducting multi-group analyses)
#' @param showlabels \code{TRUE} or \code{FALSE} (default), show the labels of
#'   the parameters in the model
#' @param constraints_examples \code{TRUE} or \code{FALSE} (default), show
#'   examples of the lavaan model syntax
#' @param outputAdditionalFitMeasures \code{TRUE} or \code{FALSE} (default),
#'   show additional fit measures (e.g., CFI, TLI, etc.)
#' @param outputRSquared \code{TRUE} or \code{FALSE} (default), show R²-values
#'   for the endogenous variables
#' @param outputMardiasCoefficients \code{TRUE} or \code{FALSE} (default),
#'   show Mardia's coefficients for multivariate skewness and kurtosis
#' @param outputObservedCovariances \code{TRUE} or \code{FALSE} (default),
#'   show the covariances and correlations between the observed values of the
#'   (manifest) variables
#' @param outputImpliedCovariances \code{TRUE} or \code{FALSE} (default), show
#'   the covariances and correlations between the model-implied / fitted values
#'   of the (manifest) variables
#' @param outputResidualCovariances \code{TRUE} or \code{FALSE} (default),
#'   show the covariances and correlations between the residuals of the
#'   (manifest) variables
#' @param outpuCombineCovariances \code{TRUE} or \code{FALSE} (default),
#'   combine the (up to) three covariance / correlation tables into one table
#'   (i.e., showing observed, model-implied and residual values for each
#'   variable combination underneath each other)
#' @param outputModificationIndices \code{TRUE} or \code{FALSE} (default),
#'   show modification indices for if certain terms were removed from the model
#' @param miHideLow \code{TRUE} or \code{FALSE} (default), hide modification
#'   indices below a certain threshold
#' @param miThreshold numeric (default: 10), set a threshold the modification
#'   indices must exceed in order to be shown
#' @param diagram \code{TRUE} or \code{FALSE} (default), produce a path
#'   diagram
#' @param diag_resid \code{TRUE} or \code{FALSE} (default), show the residuals
#'   (for the observed variables)
#' @param diag_intercepts \code{TRUE} or \code{FALSE} (default), show the
#'   variable intercepts
#' @param diag_paths Choose the values shown along the paths ("est" [coeffic.,
#'   default], "stand" [betas], "name" [labels], "hide" [nothing])
#' @param diag_type Choose the layout of the path diagram ("tree" [default],
#'   "tree2", "circle", "circle2", "spring")
#' @param diag_rotate Choose the rotation of the path diagram (placement of
#'   the exog. variables; "1": top, "2": left (default), "3": bottom, "4":
#'   right)
#' @param diag_labsize Choose the node size for the variables (default:
#'   "medium")
#' @param diag_shape_man Choose the shape for the manifest variables (default:
#'   "rectangle")
#' @param diag_shape_lat Choose the shape for the latent variables (default:
#'   "circle")
#' @param diag_abbrev Choose the length (characters) of the variable name
#'   abbreviations (default: 5)
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$model} \tab \tab \tab \tab \tab The underlying \code{lavaan} object \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$contraintsnotes} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fit$main} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fit$constraints} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fit$indices} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$coefficients} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$loadings} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$intercepts} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$defined} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$add_outputs$compModelBsl} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$add_outputs$otherFit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$add_outputs$Rsquared} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$add_outputs$mardia} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$group_covariances$covcorrObserved} \tab \tab \tab \tab \tab A covariance / correlation matrix table. \cr
#'   \code{results$group_covariances$covcorrImplied} \tab \tab \tab \tab \tab A covariance / correlation matrix table. \cr
#'   \code{results$group_covariances$covcorrResidual} \tab \tab \tab \tab \tab A covariance / correlation matrix table. \cr
#'   \code{results$group_covariances$covcorrCombined} \tab \tab \tab \tab \tab A covariance / correlation matrix table. \cr
#'   \code{results$modgroup$modInd} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pathgroup$diagrams} \tab \tab \tab \tab \tab an array of path diagrams \cr
#'   \code{results$pathgroup$notes} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
semljsyn <- function(
    data,
    code = "",
    syntax,
    fonts = "small",
    vars,
    toggle = FALSE,
    estimator = "ML",
    likelihood = "normal",
    scoretest = TRUE,
    cumscoretest = FALSE,
    se = "standard",
    bootci = "perc",
    bootN = 1000,
    ci = TRUE,
    ciWidth = 95,
    intercepts = TRUE,
    showintercepts = TRUE,
    indirect = FALSE,
    auto.fix.first = TRUE,
    std.lv = FALSE,
    cov_x = TRUE,
    cov_y = TRUE,
    multigroup,
    eq_loadings = FALSE,
    eq_intercepts = FALSE,
    eq_residuals = FALSE,
    eq_residual.covariances = FALSE,
    eq_means = FALSE,
    eq_thresholds = FALSE,
    eq_regressions = FALSE,
    eq_lv.variances = FALSE,
    eq_lv.covariances = FALSE,
    showlabels = FALSE,
    constraints_examples = FALSE,
    outputAdditionalFitMeasures = FALSE,
    outputRSquared = FALSE,
    outputMardiasCoefficients = FALSE,
    outputObservedCovariances = FALSE,
    outputImpliedCovariances = FALSE,
    outputResidualCovariances = FALSE,
    outpuCombineCovariances = FALSE,
    outputModificationIndices = FALSE,
    miHideLow = FALSE,
    miThreshold = 10,
    diagram = FALSE,
    diag_resid = FALSE,
    diag_intercepts = FALSE,
    diag_paths = "est",
    diag_type = "tree",
    diag_rotate = "2",
    diag_labsize = "medium",
    diag_shape_man = "rectangle",
    diag_shape_lat = "circle",
    diag_abbrev = "5") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("semljsyn requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- semljsynOptions$new(
        code = code,
        syntax = syntax,
        fonts = fonts,
        vars = vars,
        toggle = toggle,
        estimator = estimator,
        likelihood = likelihood,
        scoretest = scoretest,
        cumscoretest = cumscoretest,
        se = se,
        bootci = bootci,
        bootN = bootN,
        ci = ci,
        ciWidth = ciWidth,
        intercepts = intercepts,
        showintercepts = showintercepts,
        indirect = indirect,
        auto.fix.first = auto.fix.first,
        std.lv = std.lv,
        cov_x = cov_x,
        cov_y = cov_y,
        multigroup = multigroup,
        eq_loadings = eq_loadings,
        eq_intercepts = eq_intercepts,
        eq_residuals = eq_residuals,
        eq_residual.covariances = eq_residual.covariances,
        eq_means = eq_means,
        eq_thresholds = eq_thresholds,
        eq_regressions = eq_regressions,
        eq_lv.variances = eq_lv.variances,
        eq_lv.covariances = eq_lv.covariances,
        showlabels = showlabels,
        constraints_examples = constraints_examples,
        outputAdditionalFitMeasures = outputAdditionalFitMeasures,
        outputRSquared = outputRSquared,
        outputMardiasCoefficients = outputMardiasCoefficients,
        outputObservedCovariances = outputObservedCovariances,
        outputImpliedCovariances = outputImpliedCovariances,
        outputResidualCovariances = outputResidualCovariances,
        outpuCombineCovariances = outpuCombineCovariances,
        outputModificationIndices = outputModificationIndices,
        miHideLow = miHideLow,
        miThreshold = miThreshold,
        diagram = diagram,
        diag_resid = diag_resid,
        diag_intercepts = diag_intercepts,
        diag_paths = diag_paths,
        diag_type = diag_type,
        diag_rotate = diag_rotate,
        diag_labsize = diag_labsize,
        diag_shape_man = diag_shape_man,
        diag_shape_lat = diag_shape_lat,
        diag_abbrev = diag_abbrev)

    analysis <- semljsynClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

