
# This file is automatically generated, you probably don't want to edit this

semljsynOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "semljsynOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            code = "",
            syntax = NULL,
            R = "bundled",
            vars = NULL,
            output = "noEcho",
            figWidth = "",
            figHeight = "",
            toggle = FALSE,
            multigroup = NULL,
            se = "standard",
            r2ci = "fisher",
            r2test = FALSE,
            bootci = "perc",
            ci = TRUE,
            ciWidth = 95,
            bootN = 1000,
            showintercepts = TRUE,
            intercepts = TRUE,
            indirect = FALSE,
            diagram = FALSE,
            diag_paths = "est",
            diag_resid = FALSE,
            diag_labsize = "medium",
            diag_rotate = "1",
            diag_type = "circle",
            diag_shape = "rectangle",
            diag_abbrev = "0",
            cov_y = TRUE,
            cov_x = TRUE,
            constraints_examples = FALSE,
            showlabels = FALSE,
            scoretest = TRUE,
            cumscoretest = FALSE,
            estimator = "ML",
            likelihood = "normal", ...) {

            super$initialize(
                package="semlj",
                name="semljsyn",
                requiresData=TRUE,
                ...)

            private$..code <- jmvcore::OptionString$new(
                "code",
                code,
                default="",
                hidden=TRUE)
            private$..syntax <- jmvcore::OptionString$new(
                "syntax",
                syntax,
                hidden=TRUE)
            private$..R <- jmvcore::OptionList$new(
                "R",
                R,
                hidden=TRUE,
                options=list(
                    "bundled",
                    "external"),
                default="bundled")
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                hidden=TRUE,
                permitted=list(
                    "factor",
                    "numeric",
                    "id"))
            private$..output <- jmvcore::OptionList$new(
                "output",
                output,
                hidden=TRUE,
                options=list(
                    "noEcho",
                    "echo"),
                default="noEcho")
            private$..figWidth <- jmvcore::OptionString$new(
                "figWidth",
                figWidth,
                default="",
                hidden=TRUE)
            private$..figHeight <- jmvcore::OptionString$new(
                "figHeight",
                figHeight,
                default="",
                hidden=TRUE)
            private$..toggle <- jmvcore::OptionBool$new(
                "toggle",
                toggle,
                default=FALSE,
                hidden=TRUE)
            private$..multigroup <- jmvcore::OptionString$new(
                "multigroup",
                multigroup)
            private$..se <- jmvcore::OptionList$new(
                "se",
                se,
                options=list(
                    "standard",
                    "robust.sem",
                    "robust.huber.white",
                    "boot"),
                default="standard")
            private$..r2ci <- jmvcore::OptionList$new(
                "r2ci",
                r2ci,
                options=list(
                    "fisher",
                    "model"),
                default="fisher")
            private$..r2test <- jmvcore::OptionBool$new(
                "r2test",
                r2test,
                default=FALSE)
            private$..bootci <- jmvcore::OptionList$new(
                "bootci",
                bootci,
                options=list(
                    "perc",
                    "bca.simple",
                    "norm",
                    "basic"),
                default="perc")
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=TRUE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..bootN <- jmvcore::OptionNumber$new(
                "bootN",
                bootN,
                min=50,
                default=1000)
            private$..showintercepts <- jmvcore::OptionBool$new(
                "showintercepts",
                showintercepts,
                default=TRUE)
            private$..intercepts <- jmvcore::OptionBool$new(
                "intercepts",
                intercepts,
                default=TRUE)
            private$..indirect <- jmvcore::OptionBool$new(
                "indirect",
                indirect,
                default=FALSE)
            private$..diagram <- jmvcore::OptionBool$new(
                "diagram",
                diagram,
                default=FALSE)
            private$..diag_paths <- jmvcore::OptionList$new(
                "diag_paths",
                diag_paths,
                options=list(
                    "est",
                    "stand",
                    "name",
                    "hide"),
                default="est")
            private$..diag_resid <- jmvcore::OptionBool$new(
                "diag_resid",
                diag_resid,
                default=FALSE)
            private$..diag_labsize <- jmvcore::OptionList$new(
                "diag_labsize",
                diag_labsize,
                options=list(
                    "small",
                    "medium",
                    "large",
                    "vlarge"),
                default="medium")
            private$..diag_rotate <- jmvcore::OptionList$new(
                "diag_rotate",
                diag_rotate,
                options=list(
                    "1",
                    "2",
                    "3",
                    "4"),
                default="1")
            private$..diag_type <- jmvcore::OptionList$new(
                "diag_type",
                diag_type,
                options=list(
                    "circle",
                    "circle2",
                    "tree2",
                    "tree",
                    "spring"),
                default="circle")
            private$..diag_shape <- jmvcore::OptionList$new(
                "diag_shape",
                diag_shape,
                options=list(
                    "rectangle",
                    "square",
                    "circle",
                    "ellipse",
                    "diamond"),
                default="rectangle")
            private$..diag_abbrev <- jmvcore::OptionList$new(
                "diag_abbrev",
                diag_abbrev,
                options=list(
                    "0",
                    "5",
                    "10",
                    "15",
                    "20",
                    "25"),
                default="0")
            private$..cov_y <- jmvcore::OptionBool$new(
                "cov_y",
                cov_y,
                default=TRUE)
            private$..cov_x <- jmvcore::OptionBool$new(
                "cov_x",
                cov_x,
                default=TRUE)
            private$..constraints_examples <- jmvcore::OptionBool$new(
                "constraints_examples",
                constraints_examples,
                default=FALSE)
            private$..showlabels <- jmvcore::OptionBool$new(
                "showlabels",
                showlabels,
                default=FALSE)
            private$..scoretest <- jmvcore::OptionBool$new(
                "scoretest",
                scoretest,
                default=TRUE)
            private$..cumscoretest <- jmvcore::OptionBool$new(
                "cumscoretest",
                cumscoretest,
                default=FALSE)
            private$..estimator <- jmvcore::OptionList$new(
                "estimator",
                estimator,
                options=list(
                    "ML",
                    "GLS",
                    "WLS",
                    "DWLS",
                    "ULS"),
                default="ML")
            private$..likelihood <- jmvcore::OptionList$new(
                "likelihood",
                likelihood,
                options=list(
                    "normal",
                    "wishart"),
                default="normal")

            self$.addOption(private$..code)
            self$.addOption(private$..syntax)
            self$.addOption(private$..R)
            self$.addOption(private$..vars)
            self$.addOption(private$..output)
            self$.addOption(private$..figWidth)
            self$.addOption(private$..figHeight)
            self$.addOption(private$..toggle)
            self$.addOption(private$..multigroup)
            self$.addOption(private$..se)
            self$.addOption(private$..r2ci)
            self$.addOption(private$..r2test)
            self$.addOption(private$..bootci)
            self$.addOption(private$..ci)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..bootN)
            self$.addOption(private$..showintercepts)
            self$.addOption(private$..intercepts)
            self$.addOption(private$..indirect)
            self$.addOption(private$..diagram)
            self$.addOption(private$..diag_paths)
            self$.addOption(private$..diag_resid)
            self$.addOption(private$..diag_labsize)
            self$.addOption(private$..diag_rotate)
            self$.addOption(private$..diag_type)
            self$.addOption(private$..diag_shape)
            self$.addOption(private$..diag_abbrev)
            self$.addOption(private$..cov_y)
            self$.addOption(private$..cov_x)
            self$.addOption(private$..constraints_examples)
            self$.addOption(private$..showlabels)
            self$.addOption(private$..scoretest)
            self$.addOption(private$..cumscoretest)
            self$.addOption(private$..estimator)
            self$.addOption(private$..likelihood)
        }),
    active = list(
        code = function() private$..code$value,
        syntax = function() private$..syntax$value,
        R = function() private$..R$value,
        vars = function() private$..vars$value,
        output = function() private$..output$value,
        figWidth = function() private$..figWidth$value,
        figHeight = function() private$..figHeight$value,
        toggle = function() private$..toggle$value,
        multigroup = function() private$..multigroup$value,
        se = function() private$..se$value,
        r2ci = function() private$..r2ci$value,
        r2test = function() private$..r2test$value,
        bootci = function() private$..bootci$value,
        ci = function() private$..ci$value,
        ciWidth = function() private$..ciWidth$value,
        bootN = function() private$..bootN$value,
        showintercepts = function() private$..showintercepts$value,
        intercepts = function() private$..intercepts$value,
        indirect = function() private$..indirect$value,
        diagram = function() private$..diagram$value,
        diag_paths = function() private$..diag_paths$value,
        diag_resid = function() private$..diag_resid$value,
        diag_labsize = function() private$..diag_labsize$value,
        diag_rotate = function() private$..diag_rotate$value,
        diag_type = function() private$..diag_type$value,
        diag_shape = function() private$..diag_shape$value,
        diag_abbrev = function() private$..diag_abbrev$value,
        cov_y = function() private$..cov_y$value,
        cov_x = function() private$..cov_x$value,
        constraints_examples = function() private$..constraints_examples$value,
        showlabels = function() private$..showlabels$value,
        scoretest = function() private$..scoretest$value,
        cumscoretest = function() private$..cumscoretest$value,
        estimator = function() private$..estimator$value,
        likelihood = function() private$..likelihood$value),
    private = list(
        ..code = NA,
        ..syntax = NA,
        ..R = NA,
        ..vars = NA,
        ..output = NA,
        ..figWidth = NA,
        ..figHeight = NA,
        ..toggle = NA,
        ..multigroup = NA,
        ..se = NA,
        ..r2ci = NA,
        ..r2test = NA,
        ..bootci = NA,
        ..ci = NA,
        ..ciWidth = NA,
        ..bootN = NA,
        ..showintercepts = NA,
        ..intercepts = NA,
        ..indirect = NA,
        ..diagram = NA,
        ..diag_paths = NA,
        ..diag_resid = NA,
        ..diag_labsize = NA,
        ..diag_rotate = NA,
        ..diag_type = NA,
        ..diag_shape = NA,
        ..diag_abbrev = NA,
        ..cov_y = NA,
        ..cov_x = NA,
        ..constraints_examples = NA,
        ..showlabels = NA,
        ..scoretest = NA,
        ..cumscoretest = NA,
        ..estimator = NA,
        ..likelihood = NA)
)

semljsynResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "semljsynResults",
    inherit = jmvcore::Group,
    active = list(
        model = function() private$..model,
        info = function() private$.items[["info"]],
        fit = function() private$.items[["fit"]],
        models = function() private$.items[["models"]],
        pathgroup = function() private$.items[["pathgroup"]],
        contraintsnotes = function() private$.items[["contraintsnotes"]]),
    private = list(
        ..model = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Structural Equation Modeling")
            private$..model <- NULL
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Models Info",
                clearWith=list(
                    "endogenousTerms",
                    "constraints"),
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`="", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="value", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="specs", 
                        `type`="text", 
                        `title`="", 
                        `combineBelow`=TRUE)),
                refs="pathj"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    main = function() private$.items[["main"]],
                    constraints = function() private$.items[["constraints"]],
                    indices = function() private$.items[["indices"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="fit",
                            title="Overall Tests",
                            clearWith=list(
                    "endogenousTerms"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="main",
                            title="Model Tests",
                            clearWith=list(
                                "endogenous",
                                "covs",
                                "factors",
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "constraints"),
                            columns=list(
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text"),
                                list(
                                    `name`="chisq", 
                                    `title`="X\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="integer"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="constraints",
                            title="Constraints Score Tests",
                            visible=FALSE,
                            clearWith=list(
                                "endogenous",
                                "covs",
                                "factors",
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "constraints"),
                            columns=list(
                                list(
                                    `name`="type", 
                                    `type`="text", 
                                    `title`="Type", 
                                    `visible`=TRUE, 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="lhs", 
                                    `title`="Par 1", 
                                    `type`="text"),
                                list(
                                    `name`="op", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="rhs", 
                                    `title`="Par 2", 
                                    `type`="text"),
                                list(
                                    `name`="chisq", 
                                    `title`="X\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="integer"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="indices",
                            title="Fit Indices",
                            clearWith=list(
                                "endogenous",
                                "covs",
                                "factors",
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "constraints"),
                            columns=list(
                                list(
                                    `name`="aic", 
                                    `title`="AIC", 
                                    `visible`="(estimator:ML)", 
                                    `type`="number"),
                                list(
                                    `name`="bic", 
                                    `title`="BIC", 
                                    `type`="number", 
                                    `visible`="(estimator:ML)"),
                                list(
                                    `name`="bic2", 
                                    `title`="adj. BIC", 
                                    `type`="number", 
                                    `visible`="(estimator:ML)"),
                                list(
                                    `name`="srmr", 
                                    `title`="SRMR", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="rmsea", 
                                    `title`="RMSEA", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="rmsea.ci.lower", 
                                    `title`="Lower", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="rmsea.ci.upper", 
                                    `title`="Upper", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="rmsea.pvalue", 
                                    `title`="RMSEA p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    coefficients = function() private$.items[["coefficients"]],
                    loadings = function() private$.items[["loadings"]],
                    correlations = function() private$.items[["correlations"]],
                    intercepts = function() private$.items[["intercepts"]],
                    defined = function() private$.items[["defined"]],
                    contrastCodeTable = function() private$.items[["contrastCodeTable"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="models",
                            title="Estimates")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="coefficients",
                            title="Parameter Estimates",
                            refs="lavaan",
                            clearWith=list(
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "data",
                                "multigroup",
                                "code"),
                            columns=list(
                                list(
                                    `name`="lgroup", 
                                    `title`="Group", 
                                    `type`="text", 
                                    `visible`="(multigroup)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text", 
                                    `visible`="(showlabels)"),
                                list(
                                    `name`="lhs", 
                                    `title`="Dep", 
                                    `type`="text"),
                                list(
                                    `name`="rhs", 
                                    `title`="Pred", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="loadings",
                            title="Measurement Model",
                            visible=FALSE,
                            clearWith=list(
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "data",
                                "multigroup",
                                "code"),
                            columns=list(
                                list(
                                    `name`="lgroup", 
                                    `title`="Group", 
                                    `type`="text", 
                                    `visible`="(multigroup)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text", 
                                    `visible`="(showlabels)"),
                                list(
                                    `name`="lhs", 
                                    `title`="Latent", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="rhs", 
                                    `title`="Observed", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="correlations",
                            title="Variances and Covariances",
                            clearWith=list(
                                "ciType",
                                "cov_y",
                                "data",
                                "multigroup",
                                "code"),
                            columns=list(
                                list(
                                    `name`="lgroup", 
                                    `title`="Group", 
                                    `type`="text", 
                                    `visible`="(multigroup)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text", 
                                    `visible`="(showlabels)"),
                                list(
                                    `name`="lhs", 
                                    `title`="Variable 1", 
                                    `type`="text"),
                                list(
                                    `name`="rhs", 
                                    `title`="Variable 2", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="type", 
                                    `title`="Type", 
                                    `type`="text"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="intercepts",
                            title="Intercepts",
                            visible=FALSE,
                            clearWith=list(
                                "endogenous",
                                "covs",
                                "factors",
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "constraints",
                                "data",
                                "multigroup"),
                            columns=list(
                                list(
                                    `name`="lgroup", 
                                    `title`="Group", 
                                    `type`="text", 
                                    `visible`="(multigroup)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text", 
                                    `visible`="(showlabels)"),
                                list(
                                    `name`="lhs", 
                                    `title`="Variable", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Intercept", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="defined",
                            title="Defined Parameters",
                            visible=FALSE,
                            clearWith=list(
                                "endogenous",
                                "covs",
                                "factors",
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "constraints",
                                "data",
                                "multigroup"),
                            columns=list(
                                list(
                                    `name`="lhs", 
                                    `title`="Label", 
                                    `type`="text"),
                                list(
                                    `name`="desc", 
                                    `title`="Description", 
                                    `type`="text"),
                                list(
                                    `name`="rhs", 
                                    `title`="Parameter", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2", 
                                    `format`="zto"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="contrastCodeTable",
                            title="Contrasts Definition",
                            visible=FALSE,
                            columns=list(
                                list(
                                    `name`="rname", 
                                    `title`="Name", 
                                    `type`="text"),
                                list(
                                    `name`="clab", 
                                    `title`="Contrast", 
                                    `type`="text"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    diagrams = function() private$.items[["diagrams"]],
                    notes = function() private$.items[["notes"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="pathgroup",
                            title="Path Model",
                            clearWith=list(
                    "endogenous",
                    "cov_y",
                    "constraints",
                    "varcov",
                    "data",
                    "multigroup"))
                        self$add(jmvcore::Array$new(
                            options=options,
                            name="diagrams",
                            title="Path Diagrams",
                            visible="(diagram)",
                            template=jmvcore::Image$new(
                                options=options,
                                title="$key",
                                renderFun=".showDiagram",
                                width=700,
                                height=500,
                                clearWith=list(
                                    "diag_resid",
                                    "diag_paths",
                                    "diag_labsize",
                                    "diag_rotate",
                                    "diag_type",
                                    "diag_shape",
                                    "diag_abbrev",
                                    "contrasts",
                                    "endogenousTerms",
                                    "cov_y",
                                    "constraints",
                                    "data",
                                    "multigroup",
                                    "varcov")),
                            refs="semplot"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="notes",
                            title="",
                            visible=FALSE,
                            columns=list(
                                list(
                                    `name`="message", 
                                    `type`="text", 
                                    `title`="Model diagram notes"))))}))$new(options=options))
            self$add(jmvcore::Table$new(
                options=options,
                name="contraintsnotes",
                visible="(constraints_examples)",
                title="Constraints input examples",
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`="Aim"),
                    list(
                        `name`="example", 
                        `type`="text", 
                        `title`="Example"),
                    list(
                        `name`="com", 
                        `type`="text", 
                        `title`="Outcome"))))},
        .setModel=function(x) private$..model <- x))

semljsynBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "semljsynBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "semlj",
                name = "semljsyn",
                version = c(1,0,0),
                options = options,
                results = semljsynResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' SEM with lavaan syntax
#'
#' 
#' @param data .
#' @param code .
#' @param syntax .
#' @param R .
#' @param vars .
#' @param output .
#' @param figWidth .
#' @param figHeight .
#' @param toggle .
#' @param multigroup .
#' @param se .
#' @param r2ci Choose the confidence interval type
#' @param r2test .
#' @param bootci Choose the confidence interval type
#' @param ci .
#' @param ciWidth a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width for the parameter estimates
#' @param bootN number of bootstrap samples for estimating confidence
#'   intervals
#' @param showintercepts \code{TRUE} or \code{FALSE} (default), show
#'   intercepts
#' @param intercepts \code{TRUE} or \code{FALSE} (default), show intercepts
#' @param indirect \code{TRUE} or \code{FALSE} (default), show intercepts
#' @param diagram \code{TRUE} or \code{FALSE} (default), produce a path
#'   diagram
#' @param diag_paths Choose the diagram labels
#' @param diag_resid \code{TRUE} or \code{FALSE} (default), produce a path
#'   diagram
#' @param diag_labsize Choose the diagram labels
#' @param diag_rotate Choose the diagram labels
#' @param diag_type Choose the diagram labels
#' @param diag_shape Choose the diagram labels
#' @param diag_abbrev Choose the diagram labels
#' @param cov_y \code{TRUE} or \code{FALSE} (default), produce a path diagram
#' @param cov_x \code{TRUE} or \code{FALSE} (default), produce a path diagram
#' @param constraints_examples .
#' @param showlabels .
#' @param scoretest .
#' @param cumscoretest .
#' @param estimator Choose the diagram labels
#' @param likelihood Choose the diagram labels
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$model} \tab \tab \tab \tab \tab The underlying \code{lavaan} object \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fit$main} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fit$constraints} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fit$indices} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$coefficients} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$loadings} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$correlations} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$intercepts} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$defined} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$contrastCodeTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pathgroup$diagrams} \tab \tab \tab \tab \tab an array of path diagrams \cr
#'   \code{results$pathgroup$notes} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$contraintsnotes} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
semljsyn <- function(
    data,
    code = "",
    syntax,
    R = "bundled",
    vars,
    output = "noEcho",
    figWidth = "",
    figHeight = "",
    toggle = FALSE,
    multigroup,
    se = "standard",
    r2ci = "fisher",
    r2test = FALSE,
    bootci = "perc",
    ci = TRUE,
    ciWidth = 95,
    bootN = 1000,
    showintercepts = TRUE,
    intercepts = TRUE,
    indirect = FALSE,
    diagram = FALSE,
    diag_paths = "est",
    diag_resid = FALSE,
    diag_labsize = "medium",
    diag_rotate = "1",
    diag_type = "circle",
    diag_shape = "rectangle",
    diag_abbrev = "0",
    cov_y = TRUE,
    cov_x = TRUE,
    constraints_examples = FALSE,
    showlabels = FALSE,
    scoretest = TRUE,
    cumscoretest = FALSE,
    estimator = "ML",
    likelihood = "normal") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("semljsyn requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- semljsynOptions$new(
        code = code,
        syntax = syntax,
        R = R,
        vars = vars,
        output = output,
        figWidth = figWidth,
        figHeight = figHeight,
        toggle = toggle,
        multigroup = multigroup,
        se = se,
        r2ci = r2ci,
        r2test = r2test,
        bootci = bootci,
        ci = ci,
        ciWidth = ciWidth,
        bootN = bootN,
        showintercepts = showintercepts,
        intercepts = intercepts,
        indirect = indirect,
        diagram = diagram,
        diag_paths = diag_paths,
        diag_resid = diag_resid,
        diag_labsize = diag_labsize,
        diag_rotate = diag_rotate,
        diag_type = diag_type,
        diag_shape = diag_shape,
        diag_abbrev = diag_abbrev,
        cov_y = cov_y,
        cov_x = cov_x,
        constraints_examples = constraints_examples,
        showlabels = showlabels,
        scoretest = scoretest,
        cumscoretest = cumscoretest,
        estimator = estimator,
        likelihood = likelihood)

    analysis <- semljsynClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

