
# This file is automatically generated, you probably don't want to edit this

semljguiOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "semljguiOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            code = "",
            endogenous = list(
                list(label="Endogenous1", vars=list())),
            exogenous = list(
                list(label="Exogenous1", vars=list())),
            endogenousTerms = list(
                list()),
            multigroup = NULL,
            se = "standard",
            bootci = "perc",
            ci = TRUE,
            ciWidth = 95,
            bootN = 1000,
            showintercepts = TRUE,
            intercepts = TRUE,
            indirect = FALSE,
            auto.fix.first = TRUE,
            std.lv = FALSE,
            diagram = FALSE,
            diag_paths = "est",
            diag_resid = FALSE,
            diag_intercepts = FALSE,
            diag_labsize = "medium",
            diag_rotate = "2",
            diag_type = "tree",
            diag_shape_man = "rectangle",
            diag_shape_lat = "circle",
            diag_abbrev = "5",
            cov_y = TRUE,
            cov_x = TRUE,
            constraints_examples = FALSE,
            showlabels = FALSE,
            scoretest = TRUE,
            cumscoretest = FALSE,
            estimator = "ML",
            likelihood = "normal", ...) {

            super$initialize(
                package="semlj",
                name="semljgui",
                requiresData=TRUE,
                ...)

            private$..code <- jmvcore::OptionString$new(
                "code",
                code,
                default="",
                hidden=TRUE)
            private$..endogenous <- jmvcore::OptionArray$new(
                "endogenous",
                endogenous,
                default=list(
                    list(label="Endogenous1", vars=list())),
                template=jmvcore::OptionGroup$new(
                    "endogenous",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionVariables$new(
                            "vars",
                            NULL,
                            suggested=list(
                                "continuous"),
                            permitted=list(
                                "numeric")))))
            private$..exogenous <- jmvcore::OptionArray$new(
                "exogenous",
                exogenous,
                default=list(
                    list(label="Exogenous1", vars=list())),
                template=jmvcore::OptionGroup$new(
                    "exogenous",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionVariables$new(
                            "vars",
                            NULL,
                            suggested=list(
                                "continuous"),
                            permitted=list(
                                "numeric")))))
            private$..endogenousTerms <- jmvcore::OptionArray$new(
                "endogenousTerms",
                endogenousTerms,
                default=list(
                    list()),
                template=jmvcore::OptionTerms$new(
                    "endogenousTerms",
                    NULL))
            private$..multigroup <- jmvcore::OptionString$new(
                "multigroup",
                multigroup)
            private$..se <- jmvcore::OptionList$new(
                "se",
                se,
                options=list(
                    "standard",
                    "robust.sem",
                    "robust.huber.white",
                    "boot"),
                default="standard")
            private$..bootci <- jmvcore::OptionList$new(
                "bootci",
                bootci,
                options=list(
                    "perc",
                    "bca.simple",
                    "norm",
                    "basic"),
                default="perc")
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=TRUE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..bootN <- jmvcore::OptionNumber$new(
                "bootN",
                bootN,
                min=50,
                default=1000)
            private$..showintercepts <- jmvcore::OptionBool$new(
                "showintercepts",
                showintercepts,
                default=TRUE)
            private$..intercepts <- jmvcore::OptionBool$new(
                "intercepts",
                intercepts,
                default=TRUE)
            private$..indirect <- jmvcore::OptionBool$new(
                "indirect",
                indirect,
                default=FALSE)
            private$..auto.fix.first <- jmvcore::OptionBool$new(
                "auto.fix.first",
                auto.fix.first,
                default=TRUE)
            private$..std.lv <- jmvcore::OptionBool$new(
                "std.lv",
                std.lv,
                default=FALSE)
            private$..diagram <- jmvcore::OptionBool$new(
                "diagram",
                diagram,
                default=FALSE)
            private$..diag_paths <- jmvcore::OptionList$new(
                "diag_paths",
                diag_paths,
                options=list(
                    "est",
                    "stand",
                    "name",
                    "hide"),
                default="est")
            private$..diag_resid <- jmvcore::OptionBool$new(
                "diag_resid",
                diag_resid,
                default=FALSE)
            private$..diag_intercepts <- jmvcore::OptionBool$new(
                "diag_intercepts",
                diag_intercepts,
                default=FALSE)
            private$..diag_labsize <- jmvcore::OptionList$new(
                "diag_labsize",
                diag_labsize,
                options=list(
                    "small",
                    "medium",
                    "large",
                    "vlarge"),
                default="medium")
            private$..diag_rotate <- jmvcore::OptionList$new(
                "diag_rotate",
                diag_rotate,
                options=list(
                    "2",
                    "1",
                    "4",
                    "3"),
                default="2")
            private$..diag_type <- jmvcore::OptionList$new(
                "diag_type",
                diag_type,
                options=list(
                    "tree",
                    "circle",
                    "circle2",
                    "tree2",
                    "spring"),
                default="tree")
            private$..diag_shape_man <- jmvcore::OptionList$new(
                "diag_shape_man",
                diag_shape_man,
                options=list(
                    "rectangle",
                    "square",
                    "circle",
                    "ellipse",
                    "diamond"),
                default="rectangle")
            private$..diag_shape_lat <- jmvcore::OptionList$new(
                "diag_shape_lat",
                diag_shape_lat,
                options=list(
                    "circle",
                    "rectangle",
                    "square",
                    "ellipse",
                    "diamond"),
                default="circle")
            private$..diag_abbrev <- jmvcore::OptionList$new(
                "diag_abbrev",
                diag_abbrev,
                options=list(
                    "0",
                    "5",
                    "10",
                    "15",
                    "20",
                    "25"),
                default="5")
            private$..cov_y <- jmvcore::OptionBool$new(
                "cov_y",
                cov_y,
                default=TRUE)
            private$..cov_x <- jmvcore::OptionBool$new(
                "cov_x",
                cov_x,
                default=TRUE)
            private$..constraints_examples <- jmvcore::OptionBool$new(
                "constraints_examples",
                constraints_examples,
                default=FALSE)
            private$..showlabels <- jmvcore::OptionBool$new(
                "showlabels",
                showlabels,
                default=FALSE)
            private$..scoretest <- jmvcore::OptionBool$new(
                "scoretest",
                scoretest,
                default=TRUE)
            private$..cumscoretest <- jmvcore::OptionBool$new(
                "cumscoretest",
                cumscoretest,
                default=FALSE)
            private$..estimator <- jmvcore::OptionList$new(
                "estimator",
                estimator,
                options=list(
                    "ML",
                    "GLS",
                    "WLS",
                    "DWLS",
                    "ULS"),
                default="ML")
            private$..likelihood <- jmvcore::OptionList$new(
                "likelihood",
                likelihood,
                options=list(
                    "normal",
                    "wishart"),
                default="normal")

            self$.addOption(private$..code)
            self$.addOption(private$..endogenous)
            self$.addOption(private$..exogenous)
            self$.addOption(private$..endogenousTerms)
            self$.addOption(private$..multigroup)
            self$.addOption(private$..se)
            self$.addOption(private$..bootci)
            self$.addOption(private$..ci)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..bootN)
            self$.addOption(private$..showintercepts)
            self$.addOption(private$..intercepts)
            self$.addOption(private$..indirect)
            self$.addOption(private$..auto.fix.first)
            self$.addOption(private$..std.lv)
            self$.addOption(private$..diagram)
            self$.addOption(private$..diag_paths)
            self$.addOption(private$..diag_resid)
            self$.addOption(private$..diag_intercepts)
            self$.addOption(private$..diag_labsize)
            self$.addOption(private$..diag_rotate)
            self$.addOption(private$..diag_type)
            self$.addOption(private$..diag_shape_man)
            self$.addOption(private$..diag_shape_lat)
            self$.addOption(private$..diag_abbrev)
            self$.addOption(private$..cov_y)
            self$.addOption(private$..cov_x)
            self$.addOption(private$..constraints_examples)
            self$.addOption(private$..showlabels)
            self$.addOption(private$..scoretest)
            self$.addOption(private$..cumscoretest)
            self$.addOption(private$..estimator)
            self$.addOption(private$..likelihood)
        }),
    active = list(
        code = function() private$..code$value,
        endogenous = function() private$..endogenous$value,
        exogenous = function() private$..exogenous$value,
        endogenousTerms = function() private$..endogenousTerms$value,
        multigroup = function() private$..multigroup$value,
        se = function() private$..se$value,
        bootci = function() private$..bootci$value,
        ci = function() private$..ci$value,
        ciWidth = function() private$..ciWidth$value,
        bootN = function() private$..bootN$value,
        showintercepts = function() private$..showintercepts$value,
        intercepts = function() private$..intercepts$value,
        indirect = function() private$..indirect$value,
        auto.fix.first = function() private$..auto.fix.first$value,
        std.lv = function() private$..std.lv$value,
        diagram = function() private$..diagram$value,
        diag_paths = function() private$..diag_paths$value,
        diag_resid = function() private$..diag_resid$value,
        diag_intercepts = function() private$..diag_intercepts$value,
        diag_labsize = function() private$..diag_labsize$value,
        diag_rotate = function() private$..diag_rotate$value,
        diag_type = function() private$..diag_type$value,
        diag_shape_man = function() private$..diag_shape_man$value,
        diag_shape_lat = function() private$..diag_shape_lat$value,
        diag_abbrev = function() private$..diag_abbrev$value,
        cov_y = function() private$..cov_y$value,
        cov_x = function() private$..cov_x$value,
        constraints_examples = function() private$..constraints_examples$value,
        showlabels = function() private$..showlabels$value,
        scoretest = function() private$..scoretest$value,
        cumscoretest = function() private$..cumscoretest$value,
        estimator = function() private$..estimator$value,
        likelihood = function() private$..likelihood$value),
    private = list(
        ..code = NA,
        ..endogenous = NA,
        ..exogenous = NA,
        ..endogenousTerms = NA,
        ..multigroup = NA,
        ..se = NA,
        ..bootci = NA,
        ..ci = NA,
        ..ciWidth = NA,
        ..bootN = NA,
        ..showintercepts = NA,
        ..intercepts = NA,
        ..indirect = NA,
        ..auto.fix.first = NA,
        ..std.lv = NA,
        ..diagram = NA,
        ..diag_paths = NA,
        ..diag_resid = NA,
        ..diag_intercepts = NA,
        ..diag_labsize = NA,
        ..diag_rotate = NA,
        ..diag_type = NA,
        ..diag_shape_man = NA,
        ..diag_shape_lat = NA,
        ..diag_abbrev = NA,
        ..cov_y = NA,
        ..cov_x = NA,
        ..constraints_examples = NA,
        ..showlabels = NA,
        ..scoretest = NA,
        ..cumscoretest = NA,
        ..estimator = NA,
        ..likelihood = NA)
)

semljguiResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "semljguiResults",
    inherit = jmvcore::Group,
    active = list(
        model = function() private$..model,
        info = function() private$.items[["info"]],
        fit = function() private$.items[["fit"]],
        models = function() private$.items[["models"]],
        pathgroup = function() private$.items[["pathgroup"]],
        contraintsnotes = function() private$.items[["contraintsnotes"]]),
    private = list(
        ..model = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="SEM gui")
            private$..model <- NULL
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Models Info",
                clearWith=list(
                    "code"),
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`="", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="value", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="specs", 
                        `type`="text", 
                        `title`="", 
                        `combineBelow`=TRUE)),
                refs="pathj"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    main = function() private$.items[["main"]],
                    constraints = function() private$.items[["constraints"]],
                    indices = function() private$.items[["indices"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="fit",
                            title="Overall Tests",
                            clearWith=list(
                    "code"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="main",
                            title="Model Tests",
                            clearWith=list(
                                "ciType",
                                "cov_y",
                                "code"),
                            columns=list(
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text"),
                                list(
                                    `name`="chisq", 
                                    `title`="X\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="integer"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="constraints",
                            title="Constraints Score Tests",
                            visible=FALSE,
                            clearWith=list(
                                "ciType",
                                "cov_y",
                                "code"),
                            columns=list(
                                list(
                                    `name`="type", 
                                    `type`="text", 
                                    `title`="Type", 
                                    `visible`=TRUE, 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="lhs", 
                                    `title`="Par 1", 
                                    `type`="text"),
                                list(
                                    `name`="op", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="rhs", 
                                    `title`="Par 2", 
                                    `type`="text"),
                                list(
                                    `name`="chisq", 
                                    `title`="X\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="integer"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="indices",
                            title="Fit Indices",
                            clearWith=list(
                                "endogenous",
                                "covs",
                                "factors",
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "constraints"),
                            columns=list(
                                list(
                                    `name`="aic", 
                                    `title`="AIC", 
                                    `visible`="(estimator:ML)", 
                                    `type`="number"),
                                list(
                                    `name`="bic", 
                                    `title`="BIC", 
                                    `type`="number", 
                                    `visible`="(estimator:ML)"),
                                list(
                                    `name`="bic2", 
                                    `title`="adj. BIC", 
                                    `type`="number", 
                                    `visible`="(estimator:ML)"),
                                list(
                                    `name`="srmr", 
                                    `title`="SRMR", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="rmsea", 
                                    `title`="RMSEA", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="rmsea.ci.lower", 
                                    `title`="Lower", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="rmsea.ci.upper", 
                                    `title`="Upper", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="rmsea.pvalue", 
                                    `title`="RMSEA p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    coefficients = function() private$.items[["coefficients"]],
                    loadings = function() private$.items[["loadings"]],
                    correlations = function() private$.items[["correlations"]],
                    intercepts = function() private$.items[["intercepts"]],
                    defined = function() private$.items[["defined"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="models",
                            title="Estimates")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="coefficients",
                            title="Parameter Estimates",
                            refs="lavaan",
                            clearWith=list(
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "data",
                                "multigroup",
                                "code"),
                            columns=list(
                                list(
                                    `name`="lgroup", 
                                    `title`="Group", 
                                    `type`="text", 
                                    `visible`="(multigroup)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text", 
                                    `visible`="(showlabels)"),
                                list(
                                    `name`="lhs", 
                                    `title`="Dep", 
                                    `type`="text"),
                                list(
                                    `name`="rhs", 
                                    `title`="Pred", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="loadings",
                            title="Measurement Model",
                            visible=FALSE,
                            clearWith=list(
                                "ciType",
                                "contrasts",
                                "cov_y",
                                "data",
                                "multigroup",
                                "code"),
                            columns=list(
                                list(
                                    `name`="lgroup", 
                                    `title`="Group", 
                                    `type`="text", 
                                    `visible`="(multigroup)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text", 
                                    `visible`="(showlabels)"),
                                list(
                                    `name`="lhs", 
                                    `title`="Latent", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="rhs", 
                                    `title`="Observed", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="correlations",
                            title="Variances and Covariances",
                            clearWith=list(
                                "ciType",
                                "cov_y",
                                "data",
                                "multigroup",
                                "code"),
                            columns=list(
                                list(
                                    `name`="lgroup", 
                                    `title`="Group", 
                                    `type`="text", 
                                    `visible`="(multigroup)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text", 
                                    `visible`="(showlabels)"),
                                list(
                                    `name`="lhs", 
                                    `title`="Variable 1", 
                                    `type`="text"),
                                list(
                                    `name`="rhs", 
                                    `title`="Variable 2", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="type", 
                                    `title`="Type", 
                                    `type`="text"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="intercepts",
                            title="Intercepts",
                            visible=FALSE,
                            clearWith=list(
                                "ciType",
                                "cov_y",
                                "data",
                                "multigroup",
                                "code"),
                            columns=list(
                                list(
                                    `name`="lgroup", 
                                    `title`="Group", 
                                    `type`="text", 
                                    `visible`="(multigroup)", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="label", 
                                    `title`="Label", 
                                    `type`="text", 
                                    `visible`="(showlabels)"),
                                list(
                                    `name`="lhs", 
                                    `title`="Variable", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Intercept", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="defined",
                            title="Defined Parameters",
                            visible=FALSE,
                            clearWith=list(
                                "ciType",
                                "cov_y",
                                "data",
                                "multigroup",
                                "code"),
                            columns=list(
                                list(
                                    `name`="lhs", 
                                    `title`="Label", 
                                    `type`="text"),
                                list(
                                    `name`="desc", 
                                    `title`="Description", 
                                    `type`="text"),
                                list(
                                    `name`="rhs", 
                                    `title`="Parameter", 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ci)", 
                                    `format`="zto"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2", 
                                    `format`="zto"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    diagrams = function() private$.items[["diagrams"]],
                    notes = function() private$.items[["notes"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="pathgroup",
                            title="Path Model",
                            clearWith=list(
                    "cov_y",
                    "data",
                    "multigroup",
                    "code",
                    "diag_shape_man",
                    "diag_shape_lat",
                    "diag_abbrev",
                    "diag_type",
                    "diag_rotate",
                    "diag_labsize",
                    "diag_resid",
                    "diag_paths",
                    "dia_intercepts"))
                        self$add(jmvcore::Array$new(
                            options=options,
                            name="diagrams",
                            title="Path Diagrams",
                            visible="(diagram)",
                            template=jmvcore::Image$new(
                                options=options,
                                title="$key",
                                renderFun=".showDiagram",
                                width=800,
                                height=600,
                                clearWith=list(
                                    "cov_y",
                                    "data",
                                    "multigroup",
                                    "code",
                                    "diag_shape_man",
                                    "diag_shape_lat",
                                    "diag_abbrev",
                                    "diag_type",
                                    "diag_rotate",
                                    "diag_labsize",
                                    "diag_resid",
                                    "diag_paths",
                                    "diag_intercepts")),
                            refs="semplot"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="notes",
                            title="",
                            visible=FALSE,
                            columns=list(
                                list(
                                    `name`="message", 
                                    `type`="text", 
                                    `title`="Model diagram notes"))))}))$new(options=options))
            self$add(jmvcore::Table$new(
                options=options,
                name="contraintsnotes",
                visible="(constraints_examples)",
                title="Syntax examples",
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`="Aim"),
                    list(
                        `name`="example", 
                        `type`="text", 
                        `title`="Example"),
                    list(
                        `name`="com", 
                        `type`="text", 
                        `title`="Outcome"))))},
        .setModel=function(x) private$..model <- x))

semljguiBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "semljguiBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "semlj",
                name = "semljgui",
                version = c(1,0,0),
                options = options,
                results = semljguiResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Structural Equation Models
#'
#' 
#' @param data .
#' @param code .
#' @param endogenous a list containing named lists that define the
#'   \code{label} of the latent variables and the \code{vars} that belong to
#'   that latent
#' @param exogenous a list containing named lists that define the \code{label}
#'   of the latent variables and the \code{vars} that belong to that latent
#' @param endogenousTerms a list of lists specifying the models for with the
#'   mediators as dependent variables.
#' @param multigroup .
#' @param se .
#' @param bootci Choose the confidence interval type
#' @param ci .
#' @param ciWidth a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width for the parameter estimates
#' @param bootN number of bootstrap samples for estimating confidence
#'   intervals
#' @param showintercepts \code{TRUE} or \code{FALSE} (default), show
#'   intercepts
#' @param intercepts \code{TRUE} or \code{FALSE} (default), show intercepts
#' @param indirect \code{TRUE} or \code{FALSE} (default), show intercepts
#' @param auto.fix.first \code{TRUE} or \code{FALSE}
#' @param std.lv \code{TRUE} or \code{FALSE}
#' @param diagram \code{TRUE} or \code{FALSE} (default), produce a path
#'   diagram
#' @param diag_paths Choose the diagram labels
#' @param diag_resid \code{TRUE} or \code{FALSE} (default), produce a path
#'   diagram
#' @param diag_intercepts \code{TRUE} or \code{FALSE} (default), produce a
#'   path diagram
#' @param diag_labsize Choose the diagram labels
#' @param diag_rotate Choose the diagram labels
#' @param diag_type Choose the diagram labels
#' @param diag_shape_man Choose the diagram labels
#' @param diag_shape_lat Choose the diagram labels
#' @param diag_abbrev Choose the diagram labels
#' @param cov_y \code{TRUE} or \code{FALSE} (default), produce a path diagram
#' @param cov_x \code{TRUE} or \code{FALSE} (default), produce a path diagram
#' @param constraints_examples .
#' @param showlabels .
#' @param scoretest .
#' @param cumscoretest .
#' @param estimator Choose the diagram labels
#' @param likelihood Choose the diagram labels
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$model} \tab \tab \tab \tab \tab The underlying \code{lavaan} object \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fit$main} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fit$constraints} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fit$indices} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$coefficients} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$loadings} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$correlations} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$intercepts} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$defined} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pathgroup$diagrams} \tab \tab \tab \tab \tab an array of path diagrams \cr
#'   \code{results$pathgroup$notes} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$contraintsnotes} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
semljgui <- function(
    data,
    code = "",
    endogenous = list(
                list(label="Endogenous1", vars=list())),
    exogenous = list(
                list(label="Exogenous1", vars=list())),
    endogenousTerms = list(
                list()),
    multigroup,
    se = "standard",
    bootci = "perc",
    ci = TRUE,
    ciWidth = 95,
    bootN = 1000,
    showintercepts = TRUE,
    intercepts = TRUE,
    indirect = FALSE,
    auto.fix.first = TRUE,
    std.lv = FALSE,
    diagram = FALSE,
    diag_paths = "est",
    diag_resid = FALSE,
    diag_intercepts = FALSE,
    diag_labsize = "medium",
    diag_rotate = "2",
    diag_type = "tree",
    diag_shape_man = "rectangle",
    diag_shape_lat = "circle",
    diag_abbrev = "5",
    cov_y = TRUE,
    cov_x = TRUE,
    constraints_examples = FALSE,
    showlabels = FALSE,
    scoretest = TRUE,
    cumscoretest = FALSE,
    estimator = "ML",
    likelihood = "normal") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("semljgui requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- semljguiOptions$new(
        code = code,
        endogenous = endogenous,
        exogenous = exogenous,
        endogenousTerms = endogenousTerms,
        multigroup = multigroup,
        se = se,
        bootci = bootci,
        ci = ci,
        ciWidth = ciWidth,
        bootN = bootN,
        showintercepts = showintercepts,
        intercepts = intercepts,
        indirect = indirect,
        auto.fix.first = auto.fix.first,
        std.lv = std.lv,
        diagram = diagram,
        diag_paths = diag_paths,
        diag_resid = diag_resid,
        diag_intercepts = diag_intercepts,
        diag_labsize = diag_labsize,
        diag_rotate = diag_rotate,
        diag_type = diag_type,
        diag_shape_man = diag_shape_man,
        diag_shape_lat = diag_shape_lat,
        diag_abbrev = diag_abbrev,
        cov_y = cov_y,
        cov_x = cov_x,
        constraints_examples = constraints_examples,
        showlabels = showlabels,
        scoretest = scoretest,
        cumscoretest = cumscoretest,
        estimator = estimator,
        likelihood = likelihood)

    analysis <- semljguiClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

